import type { Theme } from '@emotion/react';

import type {
  BrandPalette,
  BrandSVG,
  Typography,
} from '../../models/types/theming';
import {
  GROUP_A_MAX_WIDTH,
  GROUP_B_MAX_WIDTH,
  GROUP_B_MIN_WIDTH,
  GROUP_B_ONLY,
  GROUP_D_MIN_WIDTH,
} from './fontMediaQueries';
import {
  getAtlasSize,
  getBodyCopySize,
  getBrevierSize,
  getCanonSize,
  getDoublePicaSize,
  getElephantSize,
  getFoolscapSize,
  getGreatPrimerSize,
  getImperialSize,
  getLongPrimerSize,
  getMinionSize,
  getParagonSize,
  getPicaSize,
  getRoyalSize,
  getTrafalgarSize,
} from './fontSizes';
import {
  getSansBold,
  getSansBoldItalic,
  getSansLight,
  getSansRegular,
  getSansRegularItalic,
  getSerifBold,
  getSerifLight,
  getSerifMedium,
  getSerifMediumItalic,
  getSerifRegular,
} from './fontVariants';
import gridWidths from './gridWidths';
import {
  FORCED_COLOURS,
  GROUP_0_MAX_WIDTH,
  GROUP_1_AND_GROUP_2,
  GROUP_1_MAX_WIDTH,
  GROUP_1_MIN_WIDTH,
  GROUP_1_ONLY,
  GROUP_2_MAX_WIDTH,
  GROUP_2_MIN_WIDTH,
  GROUP_2_ONLY,
  GROUP_3_MAX_WIDTH,
  GROUP_3_MIN_WIDTH,
  GROUP_3_ONLY,
  GROUP_4_MAX_WIDTH,
  GROUP_4_MIN_WIDTH,
  GROUP_4_ONLY,
  GROUP_5_MIN_WIDTH,
  POINTER,
} from './mediaQueries';
import {
  ARCHIVE_BLUE,
  BLACK,
  BLUEJAY,
  BLUEJAY_LHT,
  CHALK,
  CLOUD_DARK,
  CLOUD_LIGHT,
  CONSENT_ACTION,
  CONSENT_BACKGROUND,
  CONSENT_CONTENT,
  CONSENT_FOCUS,
  DARK_SALTIRE,
  DIM_GREY,
  EBON,
  ERROR_CORE,
  GHOST,
  GREY_1,
  GREY_2,
  GREY_3,
  GREY_4,
  GREY_5,
  GREY_6,
  GREY_7,
  GREY_8,
  GREY_10,
  GREY_11,
  GREY_15,
  GREY_16,
  KINGFISHER,
  LE_TEAL,
  LIVE_CORE,
  LIVE_DARK,
  LIVE_LIGHT,
  LIVE_MEDIUM,
  LUNAR,
  LUNAR_LIGHT,
  METAL,
  MIDNIGHT_BLACK,
  NEUTRAL_LIGHT,
  NEWSROUND_PURPLE,
  NEWSROUND_PURPLE_30,
  OAT_LHT,
  ORBIT_GREY,
  PEBBLE,
  PHILIPPINE_GREY,
  POSTBOX,
  POSTBOX_30,
  RHINO,
  SERVICE_NEUTRAL_CORE,
  SERVICE_NEUTRAL_DARK,
  SHADOW,
  SPORT_MIST,
  SPORT_SILVER,
  SPORT_YELLOW,
  SPORT_YELLOW_30,
  STONE,
  STORM,
  SUCCESS_CORE,
  WEATHER_BLUE,
  WHITE,
} from './palette';
import {
  DOUBLE,
  FULL,
  HALF,
  QUADRUPLE,
  QUINTUPLE,
  SEXTUPLE,
  TRIPLE,
} from './spacings';

export default ({
  typography,
  brandSVG,
  palette,
  isLite,
  isDarkUi,
}: {
  typography: Typography;
  palette: BrandPalette;
  brandSVG: BrandSVG;
  isLite: boolean;
  isDarkUi: boolean;
  usePWATypography?: boolean;
}): Theme => {
  const { fontVariants, script, fontFaces } = typography;
  const {
    BRAND_BACKGROUND,
    BRAND_LOGO,
    BRAND_FOREGROUND,
    BRAND_HIGHLIGHT,
    BRAND_BORDER,
  } = palette;

  const themeConfig: Theme = {
    fontSizes: {
      atlas: getAtlasSize(script),
      elephant: getElephantSize(script),
      imperial: getImperialSize(script),
      royal: getRoyalSize(script),
      foolscap: getFoolscapSize(script),
      canon: getCanonSize(script),
      trafalgar: getTrafalgarSize(script),
      paragon: getParagonSize(script),
      doublePica: getDoublePicaSize(script),
      greatPrimer: getGreatPrimerSize(script),
      bodyCopy: getBodyCopySize(script),
      pica: getPicaSize(script),
      longPrimer: getLongPrimerSize(script),
      brevier: getBrevierSize(script),
      minion: getMinionSize(script),
    },
    fontVariants: {
      sansRegular: getSansRegular(fontVariants),
      sansRegularItalic: getSansRegularItalic(fontVariants),
      sansBold: getSansBold(fontVariants),
      sansBoldItalic: getSansBoldItalic(fontVariants),
      sansLight: getSansLight(fontVariants),
      serifRegular: getSerifRegular(fontVariants),
      serifMedium: getSerifMedium(fontVariants),
      serifMediumItalic: getSerifMediumItalic(fontVariants),
      serifBold: getSerifBold(fontVariants),
      serifLight: getSerifLight(fontVariants),
    },
    fontMq: {
      GROUP_A_MAX_WIDTH,
      GROUP_B_MAX_WIDTH,
      GROUP_B_MIN_WIDTH,
      GROUP_B_ONLY,
      GROUP_D_MIN_WIDTH,
    },
    mq: {
      GROUP_0_MAX_WIDTH,
      GROUP_1_MAX_WIDTH,
      GROUP_1_MIN_WIDTH,
      GROUP_1_ONLY,
      GROUP_2_MAX_WIDTH,
      GROUP_2_MIN_WIDTH,
      GROUP_2_ONLY,
      GROUP_1_AND_GROUP_2,
      GROUP_3_MAX_WIDTH,
      GROUP_3_MIN_WIDTH,
      GROUP_3_ONLY,
      GROUP_4_MAX_WIDTH,
      GROUP_4_MIN_WIDTH,
      GROUP_4_ONLY,
      GROUP_5_MIN_WIDTH,
      FORCED_COLOURS,
      POINTER,
    },
    palette: {
      ARCHIVE_BLUE,
      BLACK,
      BLUEJAY,
      BLUEJAY_LHT,
      CHALK,
      CLOUD_DARK,
      CLOUD_LIGHT,
      CONSENT_ACTION,
      CONSENT_BACKGROUND,
      CONSENT_CONTENT,
      CONSENT_FOCUS,
      DARK_SALTIRE,
      DIM_GREY,
      EBON,
      ERROR_CORE,
      GHOST,
      GREY_1,
      GREY_2,
      GREY_3,
      GREY_4,
      GREY_5,
      GREY_6,
      GREY_7,
      GREY_8,
      GREY_10,
      GREY_11,
      GREY_15,
      GREY_16,
      KINGFISHER,
      LE_TEAL,
      LIVE_LIGHT,
      LIVE_MEDIUM,
      LIVE_DARK,
      LIVE_CORE,
      LUNAR,
      LUNAR_LIGHT,
      METAL,
      MIDNIGHT_BLACK,
      NEWSROUND_PURPLE,
      NEWSROUND_PURPLE_30,
      OAT_LHT,
      ORBIT_GREY,
      PEBBLE,
      PHILIPPINE_GREY,
      POSTBOX,
      POSTBOX_30,
      RHINO,
      NEUTRAL_LIGHT,
      SERVICE_NEUTRAL_CORE,
      SERVICE_NEUTRAL_DARK,
      SHADOW,
      SPORT_MIST,
      SPORT_SILVER,
      SPORT_YELLOW,
      SPORT_YELLOW_30,
      STONE,
      STORM,
      SUCCESS_CORE,
      WEATHER_BLUE,
      WHITE,
      BRAND_BACKGROUND,
      BRAND_LOGO,
      BRAND_FOREGROUND,
      BRAND_HIGHLIGHT,
      BRAND_BORDER,
    },
    spacings: {
      HALF,
      FULL,
      DOUBLE,
      TRIPLE,
      QUADRUPLE,
      QUINTUPLE,
      SEXTUPLE,
    },
    brandSVG,
    gridWidths,
    isLite,
    isDarkUi,
    fontFaces,
  };

  return themeConfig;
};
