import * as LIGHT_PALETTE from './palette';

const DARK_PALETTE = {
  GREY_10: LIGHT_PALETTE.LUNAR,
  GREY_2: LIGHT_PALETTE.GREY_10,
  GREY_6: LIGHT_PALETTE.GREY_3,
  METAL: LIGHT_PALETTE.GREY_3,
  EBON: LIGHT_PALETTE.GREY_2,
  POSTBOX: '#EB0000',
};

export default DARK_PALETTE;
