import * as LIGHT_PALETTE from './palette';

const DARK_PALETTE = {
  GREY_10: LIGHT_PALETTE.LUNAR,
  GREY_2: LIGHT_PALETTE.GREY_10,
  GREY_6: LIGHT_PALETTE.GREY_3,
  GREY_6_PROMO_TIME: LIGHT_PALETTE.GREY_6,
  METAL: LIGHT_PALETTE.GREY_3,
  METAL_VISITED: LIGHT_PALETTE.GREY_6,
  EBON: LIGHT_PALETTE.GREY_2,
  EBON_LINK: LIGHT_PALETTE.GREY_10,
  POSTBOX: '#EB0000',
  WHITE: LIGHT_PALETTE.GREY_3,
  WHITE_TAG: LIGHT_PALETTE.GREY_7,
  GHOST: LIGHT_PALETTE.GREY_7,
};

export default DARK_PALETTE;
