/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service nepali
 * @pathname /nepali/media-23269034
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP nepali mediaAssetPage', runAmpTests);
