/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service afrique
 * @pathname /afrique
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP afrique frontPage', runAmpTests);
