/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service afrique
 * @pathname /afrique
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical afrique frontPage', runCanonicalTests);
