/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service pidgin
 * @pathname /pidgin/23248703
 * @hasBulletedList true
 * @hasRelatedContent true
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP pidgin mediaAssetPage', runAmpTests);
