/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service pidgin
 * @pathname /pidgin/23248703
 * @hasBulletedList true
 * @hasRelatedContent true
 */

import runCanonicalTests from '../../../../pages/mediaAssetPage/canonicalTests';

describe('Canonical pidgin mediaAssetPage', runCanonicalTests);
