/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service russian
 * @pathname /russian/articles/ck7pz7re3zgo
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP russian articles', runAmpTests);
