/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service russian
 * @pathname /russian/articles/ck7pz7re3zgo
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical russian articles', runCanonicalTests);
