/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service news
 * @pathname /news/articles/cn7k01xp8kxo
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP news articles', runAmpTests);
