/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service arabic
 * @pathname /arabic/articles/c1er5mjnznzo
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical arabic articles', runCanonicalTests);
