// This file is automatically generated to provide TypeScript definitions for index.module.scss
// It allows importing styles as a typed object in TypeScript

declare module './index.module.scss' {
  export const h2: string;
  // Add more class names here if needed
  const classes: { [key: string]: string };
  export default classes;
}

declare module '*.module.scss' {
  const classes: { [key: string]: string };
  export default classes;
}

declare const styles: { [className: string]: string };
export default styles;
