/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service afaanoromoo
 * @pathname /afaanoromoo
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP afaanoromoo frontPage', runAmpTests);
