/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service afaanoromoo
 * @pathname /afaanoromoo
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical afaanoromoo frontPage', runCanonicalTests);
