/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service russian
 * @pathname /russian
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP russian frontPage', runAmpTests);
