/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service russian
 * @pathname /russian
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical russian frontPage', runCanonicalTests);
