/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service ukchina
 * @pathname /ukchina/simp
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP ukchina frontPage', runAmpTests);
