/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service ukchina
 * @pathname /ukchina/simp
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical ukchina frontPage', runCanonicalTests);
