/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service nepali
 * @pathname /nepali
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP nepali frontPage', runAmpTests);
