/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service nepali
 * @pathname /nepali
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical nepali frontPage', runCanonicalTests);
