/**
 * @service cymrufyw
 * @pathname /cymrufyw/erthyglau/c06p32z9x2mo
 *
 * THIS TEST SUITE WAS GENERATED BY A BUILD SCRIPT. DO NOT EDIT THIS FILE.
 */

import runCoreTests from '../../../../common/core.canonical';
import runAnalyticsTests from '../../../../common/analytics.canonical';
runCoreTests();
runAnalyticsTests();
