/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service azeri
 * @pathname /azeri
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP azeri frontPage', runAmpTests);
