/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service azeri
 * @pathname /azeri
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical azeri frontPage', runCanonicalTests);
