/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service hausa
 * @pathname /hausa
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP hausa frontPage', runAmpTests);
