/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service hausa
 * @pathname /hausa
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical hausa frontPage', runCanonicalTests);
