/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service japanese
 * @pathname /japanese/articles/cdd6p3r9g7jo
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP japanese articles', runAmpTests);
