/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service japanese
 * @pathname /japanese/articles/cdd6p3r9g7jo
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical japanese articles', runCanonicalTests);
