/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service pashto
 * @pathname /pashto
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP pashto frontPage', runAmpTests);
