/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service pashto
 * @pathname /pashto
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical pashto frontPage', runCanonicalTests);
