/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service uzbek
 * @pathname /uzbek
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP uzbek frontPage', runAmpTests);
