/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service amharic
 * @pathname /amharic
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP amharic frontPage', runAmpTests);
