/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service amharic
 * @pathname /amharic
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical amharic frontPage', runCanonicalTests);
