/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service sinhala
 * @pathname /sinhala/articles/c45w255zlexo
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical sinhala articles', runCanonicalTests);
