/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service gujarati
 * @pathname /gujarati/other-news-23130286
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP gujarati mediaAssetPage', runAmpTests);
