/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service gujarati
 * @pathname /gujarati/other-news-23130286
 */

import runCanonicalTests from '../../../../pages/mediaAssetPage/canonicalTests';

describe('Canonical gujarati mediaAssetPage', runCanonicalTests);
