exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "Tests/"
- "/vendor/"
- "/_test.go"
- "**/.d.ts"
- "cypress/{integration,support}/*.js"
- "src//*.test.{jsx,js}"
- "src/app/lib/config/"
