FROM node:12
WORKDIR /usr/src/app
ARG SIMORGH_PROTOCOL=http
ARG SIMORGH_HOST_URL=localhost
ARG SIMORGH_SERVER_PORT
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 7080
RUN SIMORGH_PROTOCOL=$SIMORGH_PROTOCOL SIMORGH_HOST_URL=$SIMORGH_HOST_URL npm run build:heroku
ENV SIMORGH_HOST_URL=$SIMORGH_HOST_URL
ENV SIMORGH_PROTOCOL=$SIMORGH_PROTOCOL
ENV SIMORGH_SERVER_PORT=$SIMORGH_SERVER_PORT
CMD ["npm", "run", "start:heroku"]
