FROM node:12.18

# Set container working directory
WORKDIR /app

# Adds node_modules to the PATH
ENV PATH /app/node_modules/.bin:$PATH

# Copy files required to install dependencies
COPY ["./package.json", "./package-lock.json", "/app/"]

# Install application dependencies using package-lock
RUN npm i

# Expose the express server port to the host
EXPOSE 7080

# Command to start the application when the container starts
CMD ["npm", "run", "dev"] 