const fs = require('fs');
const path = require('path');
const appDirectory = fs.realpathSync(process.cwd());
const resolvePath = relativePath => path.resolve(appDirectory, relativePath);
const BrotliPlugin = require('brotli-webpack-plugin');
const CompressionPlugin = require('compression-webpack-plugin');
const OfflinePlugin = require('offline-plugin');
const merge = require('webpack-merge');

// `shell` parameter populated via CLI, e.g. webpack --env.production  --env.platform=web
module.exports = (shell = {}) => {
  const HOST = 'localhost';
  const PORT = 7080;
  const FULL_HOST = `http://${HOST}:${PORT}`;

  const IS_CI = false;
  const IS_DEV = !shell.production;

  const baseConfig = {
    mode: shell.production ? 'production' : 'development',
    output: {
      publicPath: FULL_HOST,
      libraryTarget: 'commonjs2',
    },
    resolve: { extensions: ['.js', '.jsx'] }, // resolves `import '../Foo'` to `../Foo/index.jsx`
    module: {
      rules: [
        {
          test: /\.(js|jsx|mjs)$/,
          include: /src/,
          use: [
            {
              loader: 'babel-loader',
              options: {
                babelrc: true,
                cacheDirectory: true,
                presets: [],
              },
            },
          ],
        },
      ],
    },
  };

  const combinedConfigs = ['client', 'server'].map(app => {
    const specialisedConfig = require(`./webpack.config.${app}.js`)({
      resolvePath,
      IS_DEV,
      IS_CI,
    });
    return merge(baseConfig, specialisedConfig);
  });

  return combinedConfigs;

  if (!IS_DEV) {
    /*
      This is a hack to disable linting on the production build.
      Linting is the first object in the rules away and this removes it.
      A prod build will fail if the API changes so it is fairly safe.
    */
    appConfig.module.rules.shift();

    // Setup bundle analyser
    if (target === 'web') {
      // setup bundle splitting
      appConfig.output.filename = 'static/js/[name].[hash:8].js';
      appConfig.optimization = {
        splitChunks: {
          chunks: 'initial',
          automaticNameDelimiter: '-',
          minSize: 184320, // 180kb
          maxSize: 245760, // 240kb
          cacheGroups: {
            vendor: {
              test: /[\\/]node_modules[\\/]/,
              name: 'vendor',
            },
          },
        },
      };

      // Setup service worker and offline support
      appConfig.plugins.push(
        new OfflinePlugin({
          AppCache: false, // because it's deprecated
          appShell: '/news/articles/',
          autoUpdate: 1000 * 60 * 60 * 6, // 6 hours
          // externals means files not generated by webpack
          // an alternative would be html-webpack-plugin
          caches: 'all',
          externals: [
            'https://gel.files.bbci.co.uk/r2.302/BBCReithSans_W_Rg.woff2',
            'https://gel.files.bbci.co.uk/r2.302/BBCReithSans_W_Rg.woff',
            'https://gel.files.bbci.co.uk/r2.302/BBCReithSerif_W_Md.woff2',
            'https://gel.files.bbci.co.uk/r2.302/BBCReithSerif_W_Md.woff',

            /* Unused fonts
              - When adding fonts, be sure to add them to the globalStyles object here:
              https://github.com/BBC-News/simorgh/blob/latest/src/app/lib/globalStyles.js#L5

              'https://gel.files.bbci.co.uk/r2.302/BBCReithSans_W_Lt.woff2',
              'https://gel.files.bbci.co.uk/r2.302/BBCReithSans_W_Lt.woff',
              'https://gel.files.bbci.co.uk/r2.302/BBCReithSerif_W_Lt.woff2',
              'https://gel.files.bbci.co.uk/r2.302/BBCReithSerif_W_Lt.woff',
              'https://gel.files.bbci.co.uk/r2.302/BBCReithSerif_W_Rg.woff2',
              'https://gel.files.bbci.co.uk/r2.302/BBCReithSerif_W_Rg.woff',
              'https://gel.files.bbci.co.uk/r2.302/BBCReithSerif_W_Bd.woff2',
              'https://gel.files.bbci.co.uk/r2.302/BBCReithSerif_W_Bd.woff',
            End of unused fonts */
          ],
          ServiceWorker: {
            events: true,
            minify: true,
          },
          updateStrategy: 'changed',
        }),
        new BrotliPlugin({
          asset: '[path].br[query]',
          test: /\.js$/,
          threshold: 10240,
          minRatio: 0.8,
        }),
        new CompressionPlugin({
          algorithm: 'gzip',
          filename: '[path].gz[query]',
          test: /\.js$/,
          threshold: 10240,
          minRatio: 0.8,
        }),
      );
    }

    // Setup bundle analyser
    if (target === 'web' && !IS_CI) {
      // const defined here because it's a dev dep (breaks production build if at top of file)
      const { BundleAnalyzerPlugin } = require('webpack-bundle-analyzer'); // eslint-disable-line import/no-extraneous-dependencies, global-require
      appConfig.plugins.push(
        new BundleAnalyzerPlugin({
          analyzerMode: 'static',
          defaultSizes: 'gzip',
          generateStatsFile: true,
          openAnalyzer: false,
          reportFilename: '../../reports/webpackBundleReport.html',
          statsFilename: '../../reports/webpackBundleReport.json',
        }),
      );
    }
  }

  // This is to override bundle performance test
  if (IS_CI) {
    appConfig.performance = {
      maxAssetSize: 245760, // 240kb - individual bundles
      maxEntrypointSize: 491520, // 480kb - total bundles
    };
  }

  return appConfig;
};
