const fontPaths = [
  'fonts/IskoolaPota/bold.eot',
  'fonts/IskoolaPota/bold.ttf',
  'fonts/IskoolaPota/bold.woff',
  'fonts/IskoolaPota/normal.eot',
  'fonts/IskoolaPota/normal.ttf',
  'fonts/IskoolaPota/normal.woff',
  'fonts/Latha/bold.eot',
  'fonts/Latha/bold.ttf',
  'fonts/Latha/bold.woff',
  'fonts/Latha/normal.eot',
  'fonts/Latha/normal.ttf',
  'fonts/Latha/normal.woff',
  'fonts/Mallanna/normal.eot',
  'fonts/Mallanna/normal.ttf',
  'fonts/Mallanna/normal.woff',
  'fonts/NotoSansEthiopic/bold.eot',
  'fonts/NotoSansEthiopic/bold.ttf',
  'fonts/NotoSansEthiopic/bold.woff',
  'fonts/NotoSansEthiopic/normal.eot',
  'fonts/NotoSansEthiopic/normal.ttf',
  'fonts/NotoSansEthiopic/normal.woff',
  'fonts/Padauk/bold.eot',
  'fonts/Padauk/bold.ttf',
  'fonts/Padauk/bold.woff',
  'fonts/Padauk/normal.eot',
  'fonts/Padauk/normal.ttf',
  'fonts/Padauk/normal.woff',
  'fonts/Reith/BBCReithSans_W_Bd.woff',
  'fonts/Reith/BBCReithSans_W_Bd.woff2',
  'fonts/Reith/BBCReithSans_W_BdIt.woff',
  'fonts/Reith/BBCReithSans_W_BdIt.woff2',
  'fonts/Reith/BBCReithSans_W_ExBd.woff',
  'fonts/Reith/BBCReithSans_W_ExBd.woff2',
  'fonts/Reith/BBCReithSans_W_ExBdIt.woff',
  'fonts/Reith/BBCReithSans_W_ExBdIt.woff2',
  'fonts/Reith/BBCReithSans_W_It.woff',
  'fonts/Reith/BBCReithSans_W_It.woff2',
  'fonts/Reith/BBCReithSans_W_Lt.woff',
  'fonts/Reith/BBCReithSans_W_LtIt.woff',
  'fonts/Reith/BBCReithSans_W_Md.woff',
  'fonts/Reith/BBCReithSans_W_Md.woff2',
  'fonts/Reith/BBCReithSans_W_MdIt.woff',
  'fonts/Reith/BBCReithSans_W_MdIt.woff2',
  'fonts/Reith/BBCReithSans_W_Rg.woff',
  'fonts/Reith/BBCReithSans_W_Rg.woff2',
  'fonts/Reith/BBCReithSansCd_W_Bd.woff',
  'fonts/Reith/BBCReithSansCd_W_Bd.woff2',
  'fonts/Reith/BBCReithSansCd_W_Rg.woff',
  'fonts/Reith/BBCReithSansCd_W_Rg.woff2',
  'fonts/Reith/BBCReithSerif_W_Bd.woff',
  'fonts/Reith/BBCReithSerif_W_Bd.woff2',
  'fonts/Reith/BBCReithSerif_W_BdIt.woff',
  'fonts/Reith/BBCReithSerif_W_BdIt.woff2',
  'fonts/Reith/BBCReithSerif_W_ExBd.woff',
  'fonts/Reith/BBCReithSerif_W_ExBdIt.woff',
  'fonts/Reith/BBCReithSerif_W_It.woff',
  'fonts/Reith/BBCReithSerif_W_It.woff2',
  'fonts/Reith/BBCReithSerif_W_Lt.woff',
  'fonts/Reith/BBCReithSerif_W_Lt.woff2',
  'fonts/Reith/BBCReithSerif_W_LtIt.woff',
  'fonts/Reith/BBCReithSerif_W_LtIt.woff2',
  'fonts/Reith/BBCReithSerif_W_Md.woff',
  'fonts/Reith/BBCReithSerif_W_Md.woff2',
  'fonts/Reith/BBCReithSerif_W_MdIt.woff',
  'fonts/Reith/BBCReithSerif_W_Rg.woff',
  'fonts/Reith/BBCReithSerif_W_Rg.woff2',
  'fonts/ReithQalam/bold.woff',
  'fonts/ReithQalam/bold.woff2',
  'fonts/ReithQalam/extrabold.woff',
  'fonts/ReithQalam/extrabold.woff2',
  'fonts/ReithQalam/light.woff',
  'fonts/ReithQalam/light.woff2',
  'fonts/ReithQalam/normal.woff',
  'fonts/ReithQalam/normal.woff2',
  'fonts/ShonarBangla/bold.eot',
  'fonts/ShonarBangla/bold.ttf',
  'fonts/ShonarBangla/bold.woff',
  'fonts/ShonarBangla/normal.eot',
  'fonts/ShonarBangla/normal.ttf',
  'fonts/ShonarBangla/normal.woff',
];

export default () => {
  // Taken from: https://github.com/storybookjs/design-system/blob/master/src/utils/loadFontsForStorybook.js
  fontPaths.forEach(fontPath => {
    const fontLink = document.createElement('link');

    fontLink.rel = 'preload';
    fontLink.href = fontPath;
    fontLink.as = 'font';
    fontLink.type = `font/${fontPath.split('.')[1]}`;
    fontLink.crossOrigin = 'anonymous';
    document.head.appendChild(fontLink);
  });
};
