/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service japanese
 * @pathname /japanese
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP japanese frontPage', runAmpTests);
