/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service japanese
 * @pathname /japanese
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical japanese frontPage', runCanonicalTests);
