/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service yoruba
 * @pathname /yoruba
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP yoruba frontPage', runAmpTests);
