/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service yoruba
 * @pathname /yoruba
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical yoruba frontPage', runCanonicalTests);
