/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service thai
 * @pathname /thai/23122810
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP thai mediaAssetPage', runAmpTests);
