/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service vietnamese
 * @pathname /vietnamese/articles/c3y59g5zm19o
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP vietnamese articles', runAmpTests);
