/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service vietnamese
 * @pathname /vietnamese/articles/c3y59g5zm19o
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical vietnamese articles', runCanonicalTests);
