version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - apt-get -y install google-chrome-stable
      - npm ci
      - npm run build
  build:
    commands:
      - npm run cypress:ci -- --browser chrome
reports:
  JunitReportsTest:
    files:
      - '**/*'
    base-directory: 'cypress/results' # Location of the reports
