/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service turkce
 * @pathname /turkce/articles/c8q1ze59n25o
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical turkce articles', runCanonicalTests);
