/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service indonesia
 * @pathname /indonesia/media-23269037
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP indonesia mediaAssetPage', runAmpTests);
