/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service indonesia
 * @pathname /indonesia/media-23269037
 */

import runCanonicalTests from '../../../../pages/mediaAssetPage/canonicalTests';

describe('Canonical indonesia mediaAssetPage', runCanonicalTests);
