/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service mundo
 * @pathname /mundo/articles/ce42wzqr2mko
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP mundo articles', runAmpTests);
