/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service ukrainian
 * @pathname /ukrainian/articles/cp4l2mrejvdo
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP ukrainian articles', runAmpTests);
