/* eslint-disable react/no-danger */
import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import Document, {
  DocumentContext,
  Head,
  Html,
  Main,
  NextScript,
} from 'next/document';
import Script from 'next/script';

import { HTMLAttributes, ReactElement } from 'react';
import { Helmet, HelmetData } from 'react-helmet';
import { CacheProvider } from '@emotion/react';
import createEmotionServer from '@emotion/server/create-instance';
import createCache from '@emotion/cache';

import {
  EnvConfig,
  getProcessEnvAppVariables,
} from '#lib/utilities/getEnvConfig';

import AmpRenderer from '#server/Document/Renderers/AmpRenderer';
import LiteRenderer from '#server/Document/Renderers/LiteRenderer';
import litePageTransforms from '#server/Document/Renderers/litePageTransforms';

import NO_JS_CLASSNAME from '#app/lib/noJs.const';

import getPathExtension from '#app/utilities/getPathExtension';
import ReverbTemplate from '#src/server/Document/Renderers/ReverbTemplate';
import ComponentTracking from '#src/server/Document/Renderers/ComponentTracking';
import CanonicalToLiteRedirect from '#src/server/utilities/CanonicalToLiteRedirect';
import addOperaMiniClassScript from '#app/lib/utilities/addOperaMiniClassScript';
import handleServerLogging from '#nextjs/utilities/handleServerLogging';
import derivePageType from '../utilities/derivePageType';

type DocProps = {
  clientSideEnvVariables: EnvConfig;
  css: string;
  helmet: HelmetData;
  htmlAttrs: HTMLAttributes<HTMLHtmlElement>;
  ids: string[];
  pageType: string;
  isAmp: boolean;
  isApp: boolean;
  isLite: boolean;
  title: ReactElement;
};

const getDynamicCss = (dynamicIds: Array<string | number>): string => {
  if (!dynamicIds.length) return '';

  const manifestPath = join(
    process.cwd(),
    'build/react-loadable-manifest.json',
  );

  if (!existsSync(manifestPath)) return '';

  try {
    const manifest: Record<string, { id: number; files: string[] }> =
      JSON.parse(readFileSync(manifestPath, 'utf-8'));

    const dynamicIdSet = new Set(dynamicIds.map(String));

    const cssFiles = [
      ...new Set(
        Object.entries(manifest)
          .filter(
            ([chunkKey, chunk]) =>
              dynamicIdSet.has(chunkKey) || dynamicIdSet.has(String(chunk.id)),
          )
          .map(([, chunk]) => chunk)
          .flatMap(chunk => chunk.files.filter(f => f.endsWith('.css'))),
      ),
    ];

    return cssFiles
      .map(file => readFileSync(join(process.cwd(), 'build', file), 'utf-8'))
      .join('');
  } catch {
    return '';
  }
};

/**
 * Returns CSS files from the global CSS manifest.
 *
 * This file is generated by the build and is the canonical list of emitted CSS chunks.
 */
const getAllCssFiles = (): string[] => {
  const manifestPath = join(process.cwd(), 'build/dynamic-css-manifest.json');
  if (!existsSync(manifestPath)) {
    return [];
  }

  try {
    return JSON.parse(readFileSync(manifestPath, 'utf-8'));
  } catch {
    return [];
  }
};

/**
 * Returns CSS files that are not represented by any react-loadable entry.
 *
 * These are the chunks we must inline globally for AMP/Lite in production,
 * because they cannot be resolved from __NEXT_DATA__.dynamicIds.
 */
const getGlobalNonLoadableCssFiles = (): string[] => {
  const allCssFiles = getAllCssFiles();
  if (!allCssFiles.length) return [];

  const loadableManifestPath = join(
    process.cwd(),
    'build/react-loadable-manifest.json',
  );

  if (!existsSync(loadableManifestPath)) {
    return allCssFiles;
  }

  try {
    const loadableManifest: Record<string, { id: number; files: string[] }> =
      JSON.parse(readFileSync(loadableManifestPath, 'utf-8'));

    const loadableCssFiles = new Set(
      Object.values(loadableManifest)
        .flatMap(({ files }) => files)
        .filter(file => file.endsWith('.css')),
    );

    return allCssFiles.filter(file => !loadableCssFiles.has(file));
  } catch {
    return allCssFiles;
  }
};

const readCssFiles = (files: string[]): string => {
  return files
    .filter(file => existsSync(join(process.cwd(), 'build', file)))
    .map(file => readFileSync(join(process.cwd(), 'build', file), 'utf-8'))
    .join('');
};

/**
 * Returns CSS to inline for AMP/Lite SSR.
 *
 * Development:
 * - Inline all extracted CSS from dev-css-modules.css to avoid missing styles during HMR.
 *
 * Production:
 * - Inline per-request CSS resolved from dynamicIds (react-loadable manifest).
 * - Plus CSS chunks from dynamic-css-manifest.json that are not represented in react-loadable.
 */
const getAmpLiteCss = (dynamicIds: Array<string | number>): string => {
  const isProd = process.env.NODE_ENV === 'production';
  const devCssPath = join(process.cwd(), 'build/dev-css-modules.css');

  if (!isProd) {
    if (existsSync(devCssPath)) {
      return readFileSync(devCssPath, 'utf-8');
    }
    return '';
  }

  const dynamicCss = getDynamicCss(dynamicIds);
  const globalNonLoadableCss = readCssFiles(getGlobalNonLoadableCssFiles());

  return dynamicCss + globalNonLoadableCss;
};

export default class AppDocument extends Document<DocProps> {
  static async getInitialProps(ctx: DocumentContext) {
    const url = ctx.asPath || '';
    const pageType = derivePageType(url);

    const { isApp, isAmp, isLite } = getPathExtension(url);

    const cache = createCache({ key: 'css' });
    const { extractCritical } = createEmotionServer(cache);

    const originalRenderPage = ctx.renderPage;
    ctx.renderPage = () =>
      originalRenderPage({
        enhanceApp: App => props => (
          <CacheProvider value={cache}>
            <App {...props} />
          </CacheProvider>
        ),
      });

    const initialProps = await Document.getInitialProps(ctx);

    if (isLite) {
      initialProps.html = litePageTransforms(initialProps.html);
    }

    const { css, ids } = extractCritical(initialProps.html);

    // Read env variables from the server and expose them to the client
    const clientSideEnvVariables = getProcessEnvAppVariables();

    handleServerLogging({ ctx, pageType });

    return {
      ...initialProps,
      clientSideEnvVariables,
      css,
      helmet: Helmet.renderStatic(),
      ids,
      pageType,
      isAmp,
      isApp,
      isLite,
    };
  }

  render() {
    const {
      clientSideEnvVariables,
      css,
      helmet,
      ids,
      pageType,
      isAmp,
      isApp,
      isLite,
    } = this.props;

    const htmlAttrs = helmet.htmlAttributes.toComponent();
    const title = helmet.title.toComponent();
    const helmetMetaTags = helmet.meta.toComponent();
    const helmetLinkTags = helmet.link.toComponent();
    const helmetScriptTags = helmet.script.toComponent();

    type NextDataProps = { dynamicIds?: Array<string | number> };
    type PropsWithNextData = typeof this.props & {
      // eslint-disable-next-line no-underscore-dangle
      __NEXT_DATA__?: NextDataProps;
    };
    /* eslint-disable no-underscore-dangle */
    const dynamicIds: Array<string | number> =
      (this.props as PropsWithNextData).__NEXT_DATA__?.dynamicIds ?? [];
    /* eslint-enable no-underscore-dangle */

    const moduleCss = isAmp || isLite ? getAmpLiteCss(dynamicIds) : '';

    const ampCss = isAmp ? css + moduleCss : css;
    const liteCss = isLite ? css + moduleCss : css;

    switch (true) {
      case isAmp:
        return (
          <AmpRenderer
            bodyContent={<Main />}
            helmetLinkTags={helmetLinkTags}
            helmetMetaTags={helmetMetaTags}
            helmetScriptTags={helmetScriptTags}
            htmlAttrs={htmlAttrs}
            ids={ids}
            styles={ampCss}
            title={title}
          />
        );
      case isLite:
        return (
          <LiteRenderer
            bodyContent={<Main />}
            helmetLinkTags={helmetLinkTags}
            helmetMetaTags={helmetMetaTags}
            helmetScriptTags={helmetScriptTags}
            htmlAttrs={htmlAttrs}
            styles={liteCss}
            title={title}
          />
        );
      default:
        return (
          <Html lang="en-GB" {...htmlAttrs} className={NO_JS_CLASSNAME}>
            <Head>
              <CanonicalToLiteRedirect />
              <ReverbTemplate />
              <script
                type="text/javascript"
                dangerouslySetInnerHTML={{
                  __html: `document.documentElement.classList.remove("no-js");`,
                }}
              />
              {addOperaMiniClassScript()}
              <Script strategy="beforeInteractive">
                {`window.SIMORGH_ENV_VARS=${JSON.stringify(clientSideEnvVariables)}`}
              </Script>
              {pageType === 'live' && (
                <script src="https://www.riddle.com/embed/build-embedjs/embedV2.js" />
              )}
              {isApp && <meta name="robots" content="noindex" />}
              {title}
              {helmetMetaTags}
              {helmetLinkTags}
              <ComponentTracking
                trackComponentViews={false}
                enableStaticClickTrackingOnOperaMiniOnly
              />
              {helmetScriptTags}
              <style
                data-emotion={ids.join(' ')}
                dangerouslySetInnerHTML={{ __html: css }}
              />
            </Head>
            <body>
              <Main />
              <NextScript />
            </body>
          </Html>
        );
    }
  }
}
