/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service kyrgyz
 * @pathname /kyrgyz/23292889
 */

import runAmpTests from '../../../../pages/storyPage/ampTests';

describe('AMP kyrgyz storyPage', runAmpTests);
