/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service kyrgyz
 * @pathname /kyrgyz/23292889
 */

import runCanonicalTests from '../../../../pages/storyPage/canonicalTests';

describe('Canonical kyrgyz storyPage', runCanonicalTests);
