/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service urdu
 * @pathname /urdu/articles/cwgq7rzv172o
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP urdu articles', runAmpTests);
