/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service urdu
 * @pathname /urdu/articles/cwgq7rzv172o
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical urdu articles', runCanonicalTests);
