import _BBC_BLOCKS from './svgs/bbcBlocks';
export { _BBC_BLOCKS as BBC_BLOCKS };
import _BBC_BLOCKS_DARK_MODE from './svgs/bbcBlocksDarkMode';
export { _BBC_BLOCKS_DARK_MODE as BBC_BLOCKS_DARK_MODE };
import _coreIcons from './svgs/coreIcons';
export { _coreIcons as coreIcons };
import _mediaIcons from './svgs/mediaIcons';
export { _mediaIcons as mediaIcons };
import _navigationIcons from './svgs/navigationIcons';
export { _navigationIcons as navigationIcons };
import _afaanoromoo from './svgs/afaanoromoo';
export { _afaanoromoo as afaanoromoo };
import _afrique from './svgs/afrique';
export { _afrique as afrique };
import _amharic from './svgs/amharic';
export { _amharic as amharic };
import _arabic from './svgs/arabic';
export { _arabic as arabic };
import _archive from './svgs/archive';
export { _archive as archive };
import _azeri from './svgs/azeri';
export { _azeri as azeri };
import _bengali from './svgs/bengali';
export { _bengali as bengali };
import _burmese from './svgs/burmese';
export { _burmese as burmese };
import _cymrufyw from './svgs/cymrufyw';
export { _cymrufyw as cymrufyw };
import _gahuza from './svgs/gahuza';
export { _gahuza as gahuza };
import _gujarati from './svgs/gujarati';
export { _gujarati as gujarati };
import _hausa from './svgs/hausa';
export { _hausa as hausa };
import _hindi from './svgs/hindi';
export { _hindi as hindi };
import _igbo from './svgs/igbo';
export { _igbo as igbo };
import _indonesia from './svgs/indonesia';
export { _indonesia as indonesia };
import _japanese from './svgs/japanese';
export { _japanese as japanese };
import _korean from './svgs/korean';
export { _korean as korean };
import _kyrgyz from './svgs/kyrgyz';
export { _kyrgyz as kyrgyz };
import _learningenglish from './svgs/learningenglish';
export { _learningenglish as learningenglish };
import _marathi from './svgs/marathi';
export { _marathi as marathi };
import _mundo from './svgs/mundo';
export { _mundo as mundo };
import _naidheachdan from './svgs/naidheachdan';
export { _naidheachdan as naidheachdan };
import _nepali from './svgs/nepali';
export { _nepali as nepali };
import _news from './svgs/news';
export { _news as news };
import _newsround from './svgs/newsround';
export { _newsround as newsround };
import _pashto from './svgs/pashto';
export { _pashto as pashto };
import _persian from './svgs/persian';
export { _persian as persian };
import _pidgin from './svgs/pidgin';
export { _pidgin as pidgin };
import _portuguese from './svgs/portuguese';
export { _portuguese as portuguese };
import _punjabi from './svgs/punjabi';
export { _punjabi as punjabi };
import _russian from './svgs/russian';
export { _russian as russian };
import _scotland from './svgs/scotland';
export { _scotland as scotland };
import _serbian from './svgs/serbian';
export { _serbian as serbian };
import _sinhala from './svgs/sinhala';
export { _sinhala as sinhala };
import _somali from './svgs/somali';
export { _somali as somali };
import _sport from './svgs/sport';
export { _sport as sport };
import _swahili from './svgs/swahili';
export { _swahili as swahili };
import _tamil from './svgs/tamil';
export { _tamil as tamil };
import _telugu from './svgs/telugu';
export { _telugu as telugu };
import _thai from './svgs/thai';
export { _thai as thai };
import _tigrinya from './svgs/tigrinya';
export { _tigrinya as tigrinya };
import _turkce from './svgs/turkce';
export { _turkce as turkce };
import _urdu from './svgs/urdu';
export { _urdu as urdu };
import _ukchina from './svgs/ukchina';
export { _ukchina as ukchina };
import _ukrainian from './svgs/ukrainian';
export { _ukrainian as ukrainian };
import _uzbek from './svgs/uzbek';
export { _uzbek as uzbek };
import _vietnamese from './svgs/vietnamese';
export { _vietnamese as vietnamese };
import _weather from './svgs/weather';
export { _weather as weather };
import _yoruba from './svgs/yoruba';
export { _yoruba as yoruba };
import _zhongwen from './svgs/zhongwen';
export { _zhongwen as zhongwen };