/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service mundo
 * @pathname /mundo
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP mundo frontPage', runAmpTests);
