/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service mundo
 * @pathname /mundo
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical mundo frontPage', runCanonicalTests);
