/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service portuguese
 * @pathname /portuguese
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP portuguese frontPage', runAmpTests);
