/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service portuguese
 * @pathname /portuguese
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical portuguese frontPage', runCanonicalTests);
