/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service korean
 * @pathname /korean/media-23248686
 * @hasBulletedList true
 * @hasRelatedContent true
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP korean mediaAssetPage', runAmpTests);
