/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service korean
 * @pathname /korean/media-23248686
 * @hasBulletedList true
 * @hasRelatedContent true
 */

import runCanonicalTests from '../../../../pages/mediaAssetPage/canonicalTests';

describe('Canonical korean mediaAssetPage', runCanonicalTests);
