/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service azeri
 * @pathname /azeri/azerbaijan-23257464
 */

import runCanonicalTests from '../../../../pages/mediaAssetPage/canonicalTests';

describe('Canonical azeri mediaAssetPage', runCanonicalTests);
