/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service persian
 * @pathname /persian
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP persian frontPage', runAmpTests);
