/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service persian
 * @pathname /persian
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical persian frontPage', runCanonicalTests);
