/**
 * @service burmese
 * @pathname /burmese/articles/cn0exdy1jzvo
 *
 * THIS TEST SUITE WAS GENERATED BY A BUILD SCRIPT. DO NOT EDIT THIS FILE.
 */

import runCoreTests from '../../../../common/core.canonical';
import runAnalyticsTests from '../../../../common/analytics.canonical';
runCoreTests();
runAnalyticsTests();
