/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service bengali
 * @pathname /bengali/articles/c6p3yp5zzmeo
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP bengali articles', runAmpTests);
