/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service bengali
 * @pathname /bengali/articles/c6p3yp5zzmeo
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical bengali articles', runCanonicalTests);
