/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service uzbek
 * @pathname /uzbek/world-23053613
 * @hasRelatedContent true
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP uzbek mediaAssetPage', runAmpTests);
