/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service tigrinya
 * @pathname /tigrinya/articles/ck62z3rjwdeo
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP tigrinya articles', runAmpTests);
