/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service sinhala
 * @pathname /sinhala/23248970
 * @hasBulletedList true
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP sinhala mediaAssetPage', runAmpTests);
