/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service indonesia
 * @pathname /indonesia/articles/c0q2zq8pzvzo
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP indonesia articles', runAmpTests);
