/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service indonesia
 * @pathname /indonesia/articles/c0q2zq8pzvzo
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical indonesia articles', runCanonicalTests);
