/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service amharic
 * @pathname /amharic/news-23263266
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP amharic mediaAssetPage', runAmpTests);
