/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service marathi
 * @pathname /marathi/media-23127353
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP marathi mediaAssetPage', runAmpTests);
