/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service pidgin
 * @pathname /pidgin
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP pidgin frontPage', runAmpTests);
