/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service pashto
 * @pathname /pashto/bbc_pashto_radio/p0340yr4
 */

import runCanonicalTests from '../../../../pages/onDemandRadioEpisode/canonicalTests';

describe('Canonical pashto onDemandRadioEpisode', runCanonicalTests);
