/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service serbian
 * @pathname /serbian/cyr
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical serbian frontPage', runCanonicalTests);
