/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service scotland
 * @pathname /scotland/articles/czwj5l0n210o
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP scotland articles', runAmpTests);
