/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service zhongwen
 * @pathname /zhongwen/articles/c3xd4x9prgyo/trad
 * @hasImageWithCaption false
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP zhongwen articles', runAmpTests);
