/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service persian
 * @pathname /persian/iran-23231114
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP persian mediaAssetPage', runAmpTests);
