/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service mundo
 * @pathname /mundo/noticias-internacional-51266689
 */

import runAmpTests from '../../../../pages/storyPage/ampTests';

describe('AMP mundo storyPage', runAmpTests);
