/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service mundo
 * @pathname /mundo/noticias-internacional-51266689
 */

import runCanonicalTests from '../../../../pages/storyPage/canonicalTests';

describe('Canonical mundo storyPage', runCanonicalTests);
