/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service punjabi
 * @pathname /punjabi
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP punjabi frontPage', runAmpTests);
