/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service punjabi
 * @pathname /punjabi
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical punjabi frontPage', runCanonicalTests);
