/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service bengali
 * @pathname /bengali/bbc_bangla_radio/liveradio
 */

import runAmpTests from '../../../../pages/liveRadio/ampTests';

describe('AMP bengali liveRadio', runAmpTests);
