/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service bengali
 * @pathname /bengali/bbc_bangla_radio/liveradio
 */

import runCanonicalTests from '../../../../pages/liveRadio/canonicalTests';

describe('Canonical bengali liveRadio', runCanonicalTests);
