/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service korean
 * @pathname /korean
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical korean frontPage', runCanonicalTests);
