/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service zhongwen
 * @pathname /zhongwen/simp
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical zhongwen frontPage', runCanonicalTests);
