/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service afaanoromoo
 * @pathname /afaanoromoo/articles/c4g19kgl85ko
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical afaanoromoo articles', runCanonicalTests);
