/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service turkce
 * @pathname /turkce
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical turkce frontPage', runCanonicalTests);
