/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service tamil
 * @pathname /tamil/articles/cwl08ll3me8o
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP tamil articles', runAmpTests);
