/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service tamil
 * @pathname /tamil/articles/cwl08ll3me8o
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical tamil articles', runCanonicalTests);
