/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service kyrgyz
 * @pathname /kyrgyz/articles/c3xd4xg3rm9o
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP kyrgyz articles', runAmpTests);
