/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service kyrgyz
 * @pathname /kyrgyz/articles/c3xd4xg3rm9o
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical kyrgyz articles', runCanonicalTests);
