/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service tamil
 * @pathname /tamil
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP tamil frontPage', runAmpTests);
