/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service tamil
 * @pathname /tamil
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical tamil frontPage', runCanonicalTests);
