/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service burmese
 * @pathname /burmese/articles/cn0exdy1jzvo
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP burmese articles', runAmpTests);
