/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service hausa
 * @pathname /hausa/23269030
 * @hasBulletedList true
 */

import runCanonicalTests from '../../../../pages/mediaAssetPage/canonicalTests';

describe('Canonical hausa mediaAssetPage', runCanonicalTests);
