/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service gahuza
 * @pathname /gahuza/amakuru-23257470
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP gahuza mediaAssetPage', runAmpTests);
