/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service gahuza
 * @pathname /gahuza/amakuru-23257470
 */

import runCanonicalTests from '../../../../pages/mediaAssetPage/canonicalTests';

describe('Canonical gahuza mediaAssetPage', runCanonicalTests);
