/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service burmese
 * @pathname /burmese/bbc_burmese_radio/liveradio
 */

import runCanonicalTests from '../../../../pages/liveRadio/canonicalTests';

describe('Canonical burmese liveRadio', runCanonicalTests);
