/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service gujarati
 * @pathname /gujarati/articles/cr5el5kw591o
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP gujarati articles', runAmpTests);
