/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service gujarati
 * @pathname /gujarati/articles/cr5el5kw591o
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical gujarati articles', runCanonicalTests);
