/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service telugu
 * @pathname /telugu/articles/cq0y4008d4vo
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP telugu articles', runAmpTests);
