/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service telugu
 * @pathname /telugu/articles/cq0y4008d4vo
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical telugu articles', runCanonicalTests);
