export default {
  ADS: 'ads',
  CHARTBEAT_ANALYTICS: 'chartbeatAnalytics',
  COMSCORE_ANALYTICS: 'comscoreAnalytics',
  CPS_RECOMMENDATIONS: 'cpsRecommendations',
  ENABLE_FETCHING_TOGGLES: 'enableFetchingToggles',
  EVENT_TRACKING: 'eventTracking',
  INCLUDE: 'include',
  LIVE_RADIO_SCHEDULE: 'liveRadioSchedule',
  MEDIA_PLAYER: 'mediaPlayer',
  MOST_READ: 'mostRead',
  PRELOAD_LEAD_IMAGE: 'preloadLeadImage',
  PREROLL_ADS: 'prerollAds',
  RADIO_SCHEDULE: 'radioSchedule',
  SCRIPT_SWITCH_LINK: 'scriptLink',
  SOCIAL_EMBED: 'socialEmbed',
  CPS_SOCIAL_EMBED: 'cpsSocialEmbed',
  VARIANT_COOKIE: 'variantCookie',
};
