/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service persian
 * @pathname /persian/articles/cej3lzd5e0go
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP persian articles', runAmpTests);
