/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service bengali
 * @pathname /bengali/media-23269006
 * @hasBulletedList true
 */

import runCanonicalTests from '../../../../pages/mediaAssetPage/canonicalTests';

describe('Canonical bengali mediaAssetPage', runCanonicalTests);
