/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service uzbek
 * @pathname /uzbek/articles/cxj3rjxm6r0o
 * @hasImageWithCaption false
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical uzbek articles', runCanonicalTests);
