/**
 * @service hausa
 * @pathname /hausa/articles/c2nr6xqmnewo
 *
 * THIS TEST SUITE WAS GENERATED BY A BUILD SCRIPT. DO NOT EDIT THIS FILE.
 */

import runCoreTests from '../../../../common/core.amp';
import runAnalyticsTests from '../../../../common/analytics.amp';
runCoreTests();
runAnalyticsTests();
