/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service gujarati
 * @pathname /gujarati
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP gujarati frontPage', runAmpTests);
