/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service gujarati
 * @pathname /gujarati
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical gujarati frontPage', runCanonicalTests);
