/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service kyrgyz
 * @pathname /kyrgyz
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP kyrgyz frontPage', runAmpTests);
