/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service kyrgyz
 * @pathname /kyrgyz
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical kyrgyz frontPage', runCanonicalTests);
