import { PageTypes } from '#app/models/types/global';
import {
  ARTICLE_PAGE,
  HOME_PAGE,
  MOST_READ_PAGE,
} from '#app/routes/utils/pageTypes';
import runTestsForPage from '../../../support/helpers/runTestsForPage';
import assertScriptSwitch from './assertions';

const scriptSwitchTestSuites = [
  // Home pages Serbian
  {
    path: '/serbian/cyr',
    service: 'serbian',
    variant: 'cyr',
    otherVariant: 'lat',
    pageType: HOME_PAGE,
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/serbian/lat',
    service: 'serbian',
    variant: 'lat',
    otherVariant: 'cyr',
    pageType: HOME_PAGE,
    runforEnv: ['local', 'test', 'live'],
    tests: [assertScriptSwitch],
  },
  // Articles pages Serbian
  {
    path: '/serbian/articles/c805k05kr73o/cyr',
    service: 'serbian',
    variant: 'cyr',
    otherVariant: 'lat',
    pageType: ARTICLE_PAGE,
    runforEnv: ['local'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/serbian/articles/c805k05kr73o/lat',
    service: 'serbian',
    variant: 'lat',
    otherVariant: 'cyr',
    pageType: ARTICLE_PAGE,
    runforEnv: ['local'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/serbian/articles/c45n4pv61vno/cyr',
    service: 'serbian',
    variant: 'cyr',
    otherVariant: 'lat',
    pageType: ARTICLE_PAGE,
    runforEnv: ['test'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/serbian/articles/c45n4pv61vno/lat',
    service: 'serbian',
    variant: 'lat',
    otherVariant: 'cyr',
    pageType: ARTICLE_PAGE,
    runforEnv: ['test'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/serbian/articles/cx2g6k2k4xxo/cyr',
    service: 'serbian',
    variant: 'cyr',
    otherVariant: 'lat',
    pageType: ARTICLE_PAGE,
    runforEnv: ['live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/serbian/articles/cx2g6k2k4xxo/lat',
    service: 'serbian',
    variant: 'lat',
    otherVariant: 'cyr',
    pageType: ARTICLE_PAGE,
    runforEnv: ['live'],
    tests: [assertScriptSwitch],
  },
  // Articles pages Uzbek
  {
    path: '/uzbek/articles/cxj3rjxm6r0o/cyr',
    service: 'uzbek',
    variant: 'cyr',
    otherVariant: 'lat',
    pageType: ARTICLE_PAGE,
    runforEnv: ['local'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/uzbek/articles/cxj3rjxm6r0o/lat',
    service: 'uzbek',
    variant: 'lat',
    otherVariant: 'cyr',
    pageType: ARTICLE_PAGE,
    runforEnv: ['local'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/uzbek/articles/c7xe5yl1xeno/cyr',
    service: 'uzbek',
    variant: 'cyr',
    otherVariant: 'lat',
    pageType: ARTICLE_PAGE,
    runforEnv: ['test'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/uzbek/articles/c7xe5yl1xeno/lat',
    service: 'uzbek',
    variant: 'lat',
    otherVariant: 'cyr',
    pageType: ARTICLE_PAGE,
    runforEnv: ['test'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/uzbek/articles/ce347g8zqd0o/cyr',
    service: 'uzbek',
    variant: 'cyr',
    otherVariant: 'lat',
    pageType: ARTICLE_PAGE,
    runforEnv: ['live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/uzbek/articles/ce347g8zqd0o/lat',
    service: 'uzbek',
    variant: 'lat',
    otherVariant: 'cyr',
    pageType: ARTICLE_PAGE,
    runforEnv: ['live'],
    tests: [assertScriptSwitch],
  },
  // Articles pages Zhongwen
  {
    path: '/zhongwen/articles/c3xd4x9prgyo/trad',
    service: 'zhongwen',
    variant: 'trad',
    otherVariant: 'simp',
    pageType: ARTICLE_PAGE,
    runforEnv: ['local'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/zhongwen/articles/c3xd4x9prgyo/simp',
    service: 'zhongwen',
    variant: 'simp',
    otherVariant: 'trad',
    pageType: ARTICLE_PAGE,
    runforEnv: ['local'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/zhongwen/articles/cq17q5896n9o/trad',
    service: 'zhongwen',
    variant: 'trad',
    otherVariant: 'simp',
    pageType: ARTICLE_PAGE,
    runforEnv: ['test'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/zhongwen/articles/cq17q5896n9o/simp',
    service: 'zhongwen',
    variant: 'simp',
    otherVariant: 'trad',
    pageType: ARTICLE_PAGE,
    runforEnv: ['test'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/zhongwen/articles/cy4lej5ep15o/trad',
    service: 'zhongwen',
    variant: 'trad',
    otherVariant: 'simp',
    pageType: ARTICLE_PAGE,
    runforEnv: ['live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/zhongwen/articles/cy4lej5ep15o/simp',
    service: 'zhongwen',
    variant: 'simp',
    otherVariant: 'trad',
    pageType: ARTICLE_PAGE,
    runforEnv: ['live'],
    tests: [assertScriptSwitch],
  },
  // MAP Serbian
  {
    path: '/serbian/cyr/23279016',
    service: 'serbian',
    variant: 'cyr',
    otherVariant: 'lat',
    pageType: ARTICLE_PAGE,
    runforEnv: ['test'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/serbian/cyr/srbija-52895074',
    service: 'serbian',
    variant: 'cyr',
    otherVariant: 'lat',
    pageType: ARTICLE_PAGE,
    runforEnv: ['live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/serbian/lat/srbija-52895074',
    service: 'serbian',
    variant: 'lat',
    otherVariant: 'cyr',
    pageType: ARTICLE_PAGE,
    runforEnv: ['live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/serbian/cyr/srbija-52895074',
    service: 'serbian',
    variant: 'cyr',
    otherVariant: 'lat',
    pageType: ARTICLE_PAGE,
    runforEnv: ['live'],
    tests: [assertScriptSwitch],
  },
  // MAP Zhongwen
  {
    path: '/zhongwen/simp/uk-23283128',
    service: 'zhongwen',
    variant: 'simp',
    otherVariant: 'trad',
    pageType: ARTICLE_PAGE,
    runforEnv: ['test'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/zhongwen/trad/uk-23283128',
    service: 'zhongwen',
    variant: 'trad',
    otherVariant: 'simp',
    pageType: ARTICLE_PAGE,
    runforEnv: ['test'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/zhongwen/simp/world-53107744',
    service: 'zhongwen',
    variant: 'simp',
    otherVariant: 'trad',
    pageType: ARTICLE_PAGE,
    runforEnv: ['live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/zhongwen/trad/world-53107744',
    service: 'zhongwen',
    variant: 'trad',
    otherVariant: 'simp',
    pageType: ARTICLE_PAGE,
    runforEnv: ['live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/serbian/popular/read/cyr',
    service: 'serbian',
    variant: 'cyr',
    otherVariant: 'lat',
    pageType: MOST_READ_PAGE,
    runforEnv: ['test', 'live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/serbian/popular/read/lat',
    service: 'serbian',
    variant: 'lat',
    otherVariant: 'cyr',
    pageType: MOST_READ_PAGE,
    runforEnv: ['test', 'live'],
    tests: [assertScriptSwitch],
  },
  // Most Read zhongwen
  {
    path: '/zhongwen/popular/read/simp',
    service: 'zhongwen',
    variant: 'simp',
    otherVariant: 'trad',
    pageType: MOST_READ_PAGE,
    runforEnv: ['test', 'live'],
    tests: [assertScriptSwitch],
  },
  {
    path: '/zhongwen/popular/read/trad',
    service: 'zhongwen',
    variant: 'trad',
    otherVariant: 'simp',
    pageType: MOST_READ_PAGE,
    runforEnv: ['test', 'live'],
    tests: [assertScriptSwitch],
  },
];

runTestsForPage({
  pageType: 'all' as PageTypes,
  testSuites: [...scriptSwitchTestSuites],
});
