/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service thai
 * @pathname /thai/articles/c442rl3md0eo
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP thai articles', runAmpTests);
