/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service kyrgyz
 * @pathname /kyrgyz/bbc_kyrgyz_radio/liveradio
 */

import runAmpTests from '../../../../pages/liveRadio/ampTests';

describe('AMP kyrgyz liveRadio', runAmpTests);
