/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service cymrufyw
 * @pathname /cymrufyw/erthyglau/c06p32z9x2mo
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP cymrufyw articles', runAmpTests);
