/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service somali
 * @pathname /somali/articles/cgn6emk3jm8o
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP somali articles', runAmpTests);
