/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service somali
 * @pathname /somali/articles/cgn6emk3jm8o
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical somali articles', runCanonicalTests);
