/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service burmese
 * @pathname /burmese
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP burmese frontPage', runAmpTests);
