/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service burmese
 * @pathname /burmese
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical burmese frontPage', runCanonicalTests);
