/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service pashto
 * @pathname /pashto/articles/cyjmdl92z3ro
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP pashto articles', runAmpTests);
