/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service pashto
 * @pathname /pashto/articles/cyjmdl92z3ro
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical pashto articles', runCanonicalTests);
