/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service amharic
 * @pathname /amharic/articles/czqverekrldo
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP amharic articles', runAmpTests);
