/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service amharic
 * @pathname /amharic/articles/czqverekrldo
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical amharic articles', runCanonicalTests);
