export const LEGACY = [
  { colorName: 'ARCHIVE_BLUE ', colorCode: '#3A549C' },
  { colorName: 'BLACK ', colorCode: '#000000' },
  { colorName: 'BLUEJAY ', colorCode: '#0F556C' },
  { colorName: 'BLUEJAY_LHT ', colorCode: '#C3DEE7' },
  { colorName: 'CHALK ', colorCode: '#ECEAE7' },
  { colorName: 'CLOUD_DARK ', colorCode: '#757575' },
  { colorName: 'CLOUD_LIGHT ', colorCode: '#BABABA' },
  { colorName: 'CONSENT_ACTION ', colorCode: '#F6A21D' },
  { colorName: 'CONSENT_BACKGROUND ', colorCode: '#323232' },
  { colorName: 'CONSENT_CONTENT ', colorCode: '#BEBEBE' },
  { colorName: 'CONSENT_FOCUS ', colorCode: '#68A1F8' },
  { colorName: 'DARK_SALTIRE ', colorCode: '#23104C' },
  { colorName: 'DIM_GREY ', colorCode: '#696969' },
  { colorName: 'EBON ', colorCode: '#222222' },
  { colorName: 'GHOST ', colorCode: '#FDFDFD' },
  { colorName: 'GREY_10 ', colorCode: '#141414' },
  { colorName: 'GREY_11 ', colorCode: '#BABABA' },
  { colorName: 'GREY_2 ', colorCode: '#F6F6F6' },
  { colorName: 'GREY_3 ', colorCode: '#E6E8EA' },
  { colorName: 'GREY_4 ', colorCode: '#B0B2B4' },
  { colorName: 'GREY_5 ', colorCode: '#8A8C8E' },
  { colorName: 'GREY_6 ', colorCode: '#545658' },
  { colorName: 'GREY_7 ', colorCode: '#3A3C3E' },
  { colorName: 'GREY_8 ', colorCode: '#202224' },
  { colorName: 'KINGFISHER ', colorCode: '#11708C' },
  { colorName: 'LE_TEAL ', colorCode: '#09838B' },
  { colorName: 'LUNAR ', colorCode: '#F2F2F2' },
  { colorName: 'LUNAR_LIGHT ', colorCode: '#F8F8F8' },
  { colorName: 'METAL ', colorCode: '#6E6E73' },
  { colorName: 'MIDNIGHT_BLACK ', colorCode: '#121212' },
  { colorName: 'NEWSROUND_PURPLE ', colorCode: '#6C22D6' },
  { colorName: 'NEWSROUND_PURPLE_30 ', colorCode: '#9159A8' },
  { colorName: 'OAT_LHT ', colorCode: '#F5F3F1' },
  { colorName: 'ORBIT_GREY ', colorCode: '#4C4C4C' },
  { colorName: 'PEBBLE ', colorCode: '#AEAEB5' },
  { colorName: 'PHILIPPINE_GREY ', colorCode: '#8A8C8E' },
  { colorName: 'POSTBOX ', colorCode: '#B80000' },
  { colorName: 'POSTBOX_30 ', colorCode: '#EAB3B3' },
  { colorName: 'RHINO ', colorCode: '#5A5A5A' },
  { colorName: 'SHADOW ', colorCode: '#3F3F42' },
  { colorName: 'SPORT_MIST ', colorCode: '#F7F7F5' },
  { colorName: 'SPORT_SILVER ', colorCode: '#DBDBDB' },
  { colorName: 'SPORT_YELLOW ', colorCode: '#FFD230' },
  { colorName: 'SPORT_YELLOW_30 ', colorCode: '#BB9A31' },
  { colorName: 'STONE ', colorCode: '#D5D0CD' },
  { colorName: 'STORM ', colorCode: '#404040' },
  { colorName: 'WEATHER_BLUE ', colorCode: '#067EB3' },
  { colorName: 'WHITE ', colorCode: '#FFFFFF' },
];

export const CROSS_PLATFORM = [
  { colorName: 'SERVICE_NEUTRAL_CORE', colorCode: '#0071F1' },
  { colorName: 'SERVICE_NEUTRAL_LIGHT', colorCode: '#3092FF' },
  { colorName: 'SERVICE_NEUTRAL_DARK', colorCode: '#0051AD' },
  { colorName: 'LIVE_CORE', colorCode: '#009E9E' },
  { colorName: 'LIVE_LIGHT', colorCode: '#00CCC7' },
  { colorName: 'LIVE_DARK', colorCode: '#006666' },
  { colorName: 'SUCCESS_CORE', colorCode: '#148A00' },
  { colorName: 'SUCCESS_LIGHT', colorCode: '#49CC29' },
  { colorName: 'SUCCESS_DARK', colorCode: '#148A00' },
  { colorName: 'ALERT_CORE', colorCode: '#FFB32B' },
  { colorName: 'ALERT_LIGHT', colorCode: '#FFCE2B' },
  { colorName: 'ALERT_DARK', colorCode: '#C8871E' },
  { colorName: 'ERROR_CORE', colorCode: '#E51854' },
  { colorName: 'ERROR_LIGHT', colorCode: '#FF4060' },
  { colorName: 'ERROR_DARK', colorCode: '#E4134F' },
];

export const SERVICE = [
  { colorName: 'NEWS_CORE', colorCode: '#B80000' },
  { colorName: 'NEWS_BRIGHT', colorCode: '#EB0000' },
  { colorName: 'NEWS_LIGHT', colorCode: '#FF453A' },
];

export const FOUNDATION = [
  { colorName: 'WHITE', colorCode: '#FFFFFF' },
  { colorName: 'GREY1', colorCode: '#FEFEFE' },
  { colorName: 'GREY2', colorCode: '#F6F6F6' },
  { colorName: 'GREY3', colorCode: '#E6E8EA' },
  { colorName: 'GREY4', colorCode: '#B0B2B4' },
  { colorName: 'GREY5', colorCode: '#8A8C8E' },
  { colorName: 'GREY6', colorCode: '#545658' },
  { colorName: 'GREY7', colorCode: '#3A3C3E' },
  { colorName: 'GREY8', colorCode: '#202224' },
  { colorName: 'GREY9', colorCode: '#141618' },
  { colorName: 'GREY10', colorCode: '#141414' },
  { colorName: 'BLACK', colorCode: '#000000' },
];
