/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service punjabi
 * @pathname /punjabi/articles/c0l79lr39qyo
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP punjabi articles', runAmpTests);
