/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service punjabi
 * @pathname /punjabi/articles/c0l79lr39qyo
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical punjabi articles', runCanonicalTests);
