/**
 * @service afaanoromoo
 * @pathname /afaanoromoo/bbc_afaanoromoo_radio/liveradio
 *
 * THIS TEST SUITE WAS GENERATED BY A BUILD SCRIPT. DO NOT EDIT THIS FILE.
 */

import runCoreTests from '../../../../common/core.amp';
import runAnalyticsTests from '../../../../common/analytics.amp';
runCoreTests();
runAnalyticsTests();
it('Audio player image placeholder', () => {
  const audioPlaceholderImage = document.querySelector(
    'amp-img[src="http://localhost:7080/images/amp_audio_placeholder.png"]',
  );
  expect(audioPlaceholderImage).toBeInTheDocument();
});
it('Audio player embed', () => {
  const audioPlayerIframe = document.querySelector('amp-iframe');
  expect(audioPlayerIframe.getAttribute('src')).toMatchInlineSnapshot(
    `"https://polling.test.bbc.co.uk/ws/av-embeds/media/bbc_afaanoromoo_radio/liveradio/om/amp"`,
  );
});
