/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service serbian
 * @pathname /serbian/articles/c805k05kr73o/cyr
 * @hasImageWithCaption false
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP serbian articles', runAmpTests);
