/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service afrique
 * @pathname /afrique/articles/cz216x22106o
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP afrique articles', runAmpTests);
