/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service afrique
 * @pathname /afrique/articles/cz216x22106o
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical afrique articles', runCanonicalTests);
