/**
 * @service azeri
 * @pathname /azeri/articles/c5k08pqnzexo
 *
 * THIS TEST SUITE WAS GENERATED BY A BUILD SCRIPT. DO NOT EDIT THIS FILE.
 */

import runCoreTests from '../../../../common/core.amp';
import runAnalyticsTests from '../../../../common/analytics.amp';
runCoreTests();
runAnalyticsTests();
