/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service marathi
 * @pathname /marathi
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP marathi frontPage', runAmpTests);
