/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service marathi
 * @pathname /marathi
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical marathi frontPage', runCanonicalTests);
