/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service hausa
 * @pathname /hausa/articles/c2nr6xqmnewo
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP hausa articles', runAmpTests);
