/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service hausa
 * @pathname /hausa/articles/c2nr6xqmnewo
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical hausa articles', runCanonicalTests);
