/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service yoruba
 * @pathname /yoruba/media-23256797
 * @hasBulletedList true
 * @hasRelatedContent true
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP yoruba mediaAssetPage', runAmpTests);
