/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service somali
 * @pathname /somali/hayadeed-23269042
 */

import runCanonicalTests from '../../../../pages/mediaAssetPage/canonicalTests';

describe('Canonical somali mediaAssetPage', runCanonicalTests);
