// BBC News Article colours
export const C_EBON = '#222222';
export const C_POSTBOX = '#B80000';
export const C_STORM = '#404040';
export const C_WHITE = '#FFFFFF';
export const C_BLUEJAY = '#0F556C';
export const C_BLUEJAY_LHT = '#C3DEE7';
export const C_OAT_LHT = '#F5F3F1';
export const C_PEBBLE = '#AEAEB5';
export const C_RHINO = '#5A5A5A';
export const C_STONE = '#D5D0CD';
export const C_CHALK = '#ECEAE7';
export const C_SHADOW = '#3F3F42';
export const C_CLOUD_DARK = '#757575';
export const C_CLOUD_LIGHT = '#BABABA';
export const C_LUNAR = '#F2F2F2';
export const C_LUNAR_LIGHT = '#F8F8F8';
export const C_GHOST = '#FDFDFD';
export const C_METAL = '#6E6E73';
export const C_KINGFISHER = '#11708C';
export const C_MIDNIGHT_BLACK = '#121212';
export const C_POSTBOX_30 = '#EAB3B3';
export const C_GREY_2 = '#F6F6F6';

// Colours from other BBC services
export const C_CONSENT_BACKGROUND = '#323232';
export const C_CONSENT_ACTION = '#F6A21D';
export const C_CONSENT_CONTENT = '#BEBEBE';
export const C_CONSENT_FOCUS = '#68A1F8';
export const C_ORBIT_GREY = '#4C4C4C';
export const C_DARK_SALTIRE = '#23104C';
export const C_WEATHER_BLUE = '#067EB3';
export const C_ARCHIVE_BLUE = '#3A549C';
export const C_LE_TEAL = '#09838B';
export const C_NEWSROUND_PURPLE = '#6C22D6';
export const C_NEWSROUND_PURPLE_30 = '#9159A8';
export const C_SPORT_YELLOW = '#FFD230';
export const C_SPORT_YELLOW_30 = '#BB9A31';
export const C_SPORT_SILVER = '#DBDBDB';
export const C_SPORT_MIST = '#F7F7F5';
export const C_BLACK = '#000000';
export const C_GREY_6 = '#545658';
export const C_GREY_8 = '#202224';

// Colours introduced by Chameleon
export const C_DIM_GREY = '#696969';
export const C_GREY_3 = '#E6E8EA';
export const C_GREY_5 = '#8A8C8E';
export const C_GREY_10 = '#141414';
export const C_GREY_11 = '#BABABA';
