/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service vietnamese
 * @pathname /vietnamese/popular/read
 */

import runAmpTests from '../../../../pages/mostReadPage/ampTests';

describe('AMP vietnamese mostReadPage', runAmpTests);
