/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service vietnamese
 * @pathname /vietnamese/popular/read
 */

import runCanonicalTests from '../../../../pages/mostReadPage/canonicalTests';

describe('Canonical vietnamese mostReadPage', runCanonicalTests);
