/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service ukchina
 * @pathname /ukchina/articles/c0e8weny66ko/trad
 * @hasImageWithCaption false
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP ukchina articles', runAmpTests);
