/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service hindi
 * @pathname /hindi/articles/c0469479x9xo
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP hindi articles', runAmpTests);
