/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service hindi
 * @pathname /hindi/articles/c0469479x9xo
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical hindi articles', runCanonicalTests);
