/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service indonesia
 * @pathname /indonesia/bbc_indonesian_radio/w172xh267fpn19l
 */

import runCanonicalTests from '../../../../pages/onDemandRadioEpisode/canonicalTests';

describe('Canonical indonesia onDemandRadioEpisode', runCanonicalTests);
