/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service swahili
 * @pathname /swahili/articles/czjqge2jwn2o
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical swahili articles', runCanonicalTests);
