/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service zhongwen
 * @pathname /zhongwen/trad
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP zhongwen frontPage', runAmpTests);
