/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service telugu
 * @pathname /telugu
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical telugu frontPage', runCanonicalTests);
