/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service gahuza
 * @pathname /gahuza/articles/cey23zx8wx8o
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP gahuza articles', runAmpTests);
