/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service gahuza
 * @pathname /gahuza/articles/cey23zx8wx8o
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical gahuza articles', runCanonicalTests);
