/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service urdu
 * @pathname /urdu
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP urdu frontPage', runAmpTests);
