/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service urdu
 * @pathname /urdu
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical urdu frontPage', runCanonicalTests);
