/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service turkce
 * @pathname /turkce/media-23268997
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP turkce mediaAssetPage', runAmpTests);
