/**
 * @service korean
 * @pathname /korean/articles/c3mn1lvz65xo
 *
 * THIS TEST SUITE WAS GENERATED BY A BUILD SCRIPT. DO NOT EDIT THIS FILE.
 */

import runCoreTests from '../../../../common/core.amp';
import runAnalyticsTests from '../../../../common/analytics.amp';
runCoreTests();
runAnalyticsTests();
