/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service urdu
 * @pathname /urdu/world-23268929
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP urdu mediaAssetPage', runAmpTests);
