/**
 * @service serbian
 * @pathname /serbian/articles/c805k05kr73o/cyr
 *
 * THIS TEST SUITE WAS GENERATED BY A BUILD SCRIPT. DO NOT EDIT THIS FILE.
 */

import runCrossPlatformTests from '../../../../../pages/articles/crossPlatformTests';
import runCanonicalTests from '../../../../../pages/articles/canonicalTests';
describe(platform.toUpperCase(), () => {
  describe(pageType, () => {
    runCrossPlatformTests();
    runCanonicalTests();
  });
});
