/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service sinhala
 * @pathname /sinhala
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP sinhala frontPage', runAmpTests);
