/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service sinhala
 * @pathname /sinhala
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical sinhala frontPage', runCanonicalTests);
