/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service somali
 * @pathname /somali
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP somali frontPage', runAmpTests);
