/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service somali
 * @pathname /somali
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical somali frontPage', runCanonicalTests);
