/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service naidheachdan
 * @pathname /naidheachdan/sgeulachdan/c18q7nedn2ko
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP naidheachdan articles', runAmpTests);
