/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service bengali
 * @pathname /bengali
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP bengali frontPage', runAmpTests);
