/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service bengali
 * @pathname /bengali
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical bengali frontPage', runCanonicalTests);
