/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service pidgin
 * @pathname /pidgin/articles/cwl08rd38l6o
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP pidgin articles', runAmpTests);
