/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service pidgin
 * @pathname /pidgin/articles/cwl08rd38l6o
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical pidgin articles', runCanonicalTests);
