/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service ukrainian
 * @pathname /ukrainian
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP ukrainian frontPage', runAmpTests);
