/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service ukrainian
 * @pathname /ukrainian
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical ukrainian frontPage', runCanonicalTests);
