/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service vietnamese
 * @pathname /vietnamese
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP vietnamese frontPage', runAmpTests);
