/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service vietnamese
 * @pathname /vietnamese
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical vietnamese frontPage', runCanonicalTests);
