const simorghLaunchDates = {
  afaanoromoo: {
    articles: 'Sept 2019',
    frontPage: '5th Feb 2020',
    liveRadio: '30th Sept 2019',
    mediaAssetPage: '6th Feb 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  afrique: {
    articles: 'Sept 2019',
    frontPage: '',
    liveRadio: '10th Jan 2020',
    mediaAssetPage: '',
    photoGalleryPage: '',
    storyPage: '',
  },
  amharic: {
    articles: 'Sept 2019',
    frontPage: '5th Feb 2020',
    liveRadio: '30th Sept 2019',
    mediaAssetPage: '6th Feb 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  arabic: {
    articles: 'Sept 2019',
    frontPage: '',
    liveRadio: '4th Feb 2020',
    mediaAssetPage: '',
    photoGalleryPage: '',
    storyPage: '',
  },
  archive: {},
  azeri: {
    articles: 'Sept 2019',
    frontPage: '26th Sept 2019',
    mediaAssetPage: '27th Feb 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  bengali: {
    articles: 'Sept 2019',
    frontPage: '5th Feb 2020',
    liveRadio: '10th Jan 2020',
    mediaAssetPage: '5th March 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  burmese: {
    articles: 'Sept 2019',
    frontPage: '19th Feb 2020',
    liveRadio: '10th Jan 2020',
    mediaAssetPage: '5th March 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  cymrufyw: {
    articles: 'Sept 2019',
    frontPage: '',
  },
  gahuza: {
    articles: 'Sept 2019',
    frontPage: '19th Feb 2020',
    liveRadio: '10th Jan 2020',
    mediaAssetPage: '27th Feb 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  gujarati: {
    articles: 'Sept 2019',
    frontPage: '13th Jan 2020',
    mediaAssetPage: '6th Feb 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  hausa: {
    articles: 'Sept 2019',
    frontPage: '',
    liveRadio: '30th Jan 2020',
    mediaAssetPage: '5th March 2020',
    photoGalleryPage: '24th March 2020',
    storyPage: '',
  },
  hindi: {
    articles: 'Sept 2019',
    frontPage: '2nd April 2020',
    liveRadio: '4th Feb 2020',
    mediaAssetPage: '',
    photoGalleryPage: '',
    storyPage: '',
  },
  igbo: {
    articles: 'Sept 2019',
    frontPage: '15th July 2019',
    mediaAssetPage: '16th Jan 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  indonesia: {
    articles: 'Sept 2019',
    frontPage: '26th Feb 2020',
    liveRadio: '30th Sept 2019',
    mediaAssetPage: '5th March 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  japanese: {
    articles: 'Sept 2019',
    frontPage: '26th Sept 2019',
    mediaAssetPage: '',
    photoGalleryPage: '',
    storyPage: '',
  },
  korean: {
    articles: 'Sept 2019',
    frontPage: '',
    liveRadio: '30th Sept 2019',
    mediaAssetPage: '6th Feb 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  kyrgyz: {
    articles: 'Sept 2019',
    frontPage: '26th Sept 2019',
    liveRadio: '10th Jan 2020',
    mediaAssetPage: '27th Feb 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  marathi: {
    articles: 'Sept 2019',
    frontPage: '13th Jan 2020',
    mediaAssetPage: '6th Feb 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  mundo: {
    articles: 'Sept 2019',
    frontPage: '2nd April 2020',
    mediaAssetPage: '',
    photoGalleryPage: '24th March 2020',
    storyPage: '',
  },
  naidheachdan: {
    articles: 'Sept 2019',
    frontPage: '',
    photoGalleryPage: '',
    storyPage: '',
  },
  nepali: {
    articles: 'Sept 2019',
    frontPage: '5th Feb 2020',
    liveRadio: '14th Jan 2020',
    mediaAssetPage: '5th March 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  news: {
    articles: '1st April 2019',
    frontPage: '',
  },
  pashto: {
    articles: 'Sept 2019',
    frontPage: '',
    liveRadio: '14th Jan 2020',
    mediaAssetPage: '5th March 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  persian: {
    articles: 'Sept 2019',
    frontPage: '',
    liveRadio: '4th Feb 2020',
    mediaAssetPage: '27th Feb 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  pidgin: {
    articles: 'Sept 2019',
    frontPage: '15th July 2019',
    mediaAssetPage: '16th Jan 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  portuguese: {
    articles: 'Sept 2019',
    frontPage: '31st March 2020',
    mediaAssetPage: '',
    photoGalleryPage: '',
    storyPage: '',
  },
  punjabi: {
    articles: 'Sept 2019',
    frontPage: '10th Sept 2019',
    mediaAssetPage: '6th Feb 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  russian: {
    articles: 'Sept 2019',
    frontPage: '2nd April 2020',
    mediaAssetPage: '',
    photoGalleryPage: '24th March 2020',
    storyPage: '',
  },
  scotland: {
    articles: 'Sept 2019',
    frontPage: '',
  },
  serbianCyr: {
    articles: 'Sept 2019',
    frontPage: '17th March 2020',
    mediaAssetPage: '',
    photoGalleryPage: '24th March 2020',
    storyPage: '',
  },
  serbianLat: {
    articles: 'Sept 2019',
    frontPage: '17th March 2020',
    mediaAssetPage: '',
    photoGalleryPage: '24th March 2020',
    storyPage: '',
  },
  sinhala: {
    articles: 'Sept 2019',
    frontPage: '5th Feb 2020',
    liveRadio: '14th Jan 2020',
    mediaAssetPage: '27th Feb 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  somali: {
    articles: 'Sept 2019',
    frontPage: '',
    liveRadio: '30th Jan 2020',
    mediaAssetPage: '5th March 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  sport: {
    articles: 'Sept 2019',
    frontPage: '',
  },
  swahili: {
    articles: 'Sept 2019',
    frontPage: '',
    liveRadio: '10th Jan 2020',
    mediaAssetPage: '5th March 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  tamil: {
    articles: 'Sept 2019',
    frontPage: '13th Jan 2020',
    liveRadio: '14th Jan 2020',
    mediaAssetPage: '5th March 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  telugu: {
    articles: 'Sept 2019',
    frontPage: '13th Jan 2020',
    mediaAssetPage: '6th Feb 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  thai: {
    articles: 'Sept 2019',
    frontPage: '19th Aug 2019',
    mediaAssetPage: '6th Feb 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  tigrinya: {
    articles: 'Sept 2019',
    frontPage: '5th Feb 2020',
    liveRadio: '30th Sept 2019',
    mediaAssetPage: '6th Feb 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  turkce: {
    articles: 'Sept 2019',
    frontPage: '3rd March 2020',
    mediaAssetPage: '5th March 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  ukchinaSimp: {
    articles: 'Sept 2019',
    frontPage: '17th March 2020',
    mediaAssetPage: '',
    photoGalleryPage: '24th March 2020',
    storyPage: '',
  },
  ukchinaTrad: {
    articles: 'Sept 2019',
    frontPage: '17th March 2020',
    mediaAssetPage: '',
    photoGalleryPage: '24th March 2020',
    storyPage: '',
  },
  ukrainian: {
    articles: 'Sept 2019',
    frontPage: '17th March 2020',
    mediaAssetPage: '26th March 2020',
    photoGalleryPage: '24th March 2020',
    storyPage: '',
  },
  urdu: {
    articles: 'Sept 2019',
    frontPage: '3rd March 2020',
    liveRadio: '4th Feb 2020',
    mediaAssetPage: '5th March 2020',
    photoGalleryPage: '24th March 2020',
    storyPage: '',
  },
  uzbek: {
    articles: 'Sept 2019',
    frontPage: '13th Jan 2020',
    liveRadio: '4th Feb 2020',
    mediaAssetPage: '26th March 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  vietnamese: {
    articles: 'Sept 2019',
    frontPage: '3rd March 2020',
    mediaAssetPage: '27th Feb 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  yoruba: {
    articles: 'Sept 2019',
    frontPage: 'July 15th 2019',
    mediaAssetPage: '16th Jan 2020',
    photoGalleryPage: '',
    storyPage: '',
  },
  zhongwenSimp: {
    articles: 'Sept 2019',
    frontPage: '31st March 2020',
    photoGalleryPage: '24th March 2020',
    storyPage: '',
  },
  zhongwenTrad: {
    articles: 'Sept 2019',
    frontPage: '31st March 2020',
    photoGalleryPage: '24th March 2020',
    storyPage: '',
  },
};

module.exports = simorghLaunchDates;
