/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service portuguese
 * @pathname /portuguese/articles/cd61pm8gzmpo
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP portuguese articles', runAmpTests);
