/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service portuguese
 * @pathname /portuguese/articles/cd61pm8gzmpo
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical portuguese articles', runCanonicalTests);
