/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service telugu
 * @pathname /telugu/international-23263261
 * @hasBulletedList true
 */

import runCanonicalTests from '../../../../pages/mediaAssetPage/canonicalTests';

describe('Canonical telugu mediaAssetPage', runCanonicalTests);
