const servicesWithRadioOrTv = {
  afaanoromoo: ['bbc_oromo_radio', 'bbc_afaanoromoo_radio'],
  afrique: ['bbc_afrique_radio', 'bbc_afrique_tv'],
  amharic: ['bbc_amharic_radio'],
  arabic: ['bbc_arabic_radio'],
  bengali: ['bbc_bangla_radio'],
  burmese: ['bbc_burmese_radio', 'bbc_burmese_tv'],
  gahuza: ['bbc_gahuza_radio'],
  gujarati: ['bbc_gujarati_tv'],
  hausa: ['bbc_hausa_radio', 'bbc_hausa_tv'],
  hindi: ['bbc_hindi_radio', 'bbc_hindi_tv'],
  igbo: ['bbc_igbo_radio'],
  indonesia: ['bbc_indonesian_radio'],
  marathi: ['bbc_marathi_tv'],
  korean: ['bbc_korean_radio'],
  kyrgyz: ['bbc_kyrgyz_radio', 'bbc_kyrgyz_tv'],
  nepali: ['bbc_nepali_radio'],
  pashto: ['bbc_pashto_radio', 'bbc_pashto_tv'],
  persian: ['bbc_persian_radio', 'bbc_dari_radio', 'bbc_persian_tv'],
  pidgin: ['bbc_pidgin_radio'],
  russian: ['bbc_russian_radio', 'bbc_russian_tv'],
  sinhala: ['bbc_sinhala_radio'],
  somali: ['bbc_somali_radio', 'bbc_somali_tv'],
  swahili: ['bbc_swahili_radio', 'bbc_swahili_tv'],
  tamil: ['bbc_tamil_radio', 'bbc_tamil_tv'],
  telugu: ['bbc_telugu_tv'],
  tigrinya: ['bbc_tigrinya_radio'],
  ukrainian: ['bbc_ukrainian_tv'],
  urdu: ['bbc_urdu_radio', 'bbc_urdu_tv'],
  uzbek: ['bbc_uzbek_radio', 'bbc_uzbek_tv'],
  yoruba: ['bbc_yoruba_radio'],
  zhongwen: ['bbc_cantonese_radio'],
};

export default servicesWithRadioOrTv;
