export const servicesWithRadio = {
  hausa: ['bbc_hausa_radio'],
  persian: ['bbc_persian_radio', 'bbc_dari_radio'],
  tigrinya: ['bbc_tigrinya_radio'],
  urdu: ['bbc_urdu_radio'],
  arabic: ['bbc_arabic_radio'],
  pashto: ['bbc_pashto_radio'],
  uzbek: ['bbc_uzbek_radio'],
  pidgin: ['bbc_pidgin_radio'],
  afaanoromoo: ['bbc_oromo_radio'], // how to handle vanity URL of bbc_afaanoromoo_radio ?
  korean: ['bbc_korean_radio'],
  igbo: ['bbc_igbo_radio'],
  nepali: ['bbc_nepali_radio'],
  swahili: ['bbc_swahili_radio'],
  kyrgyz: ['bbc_kyrgyz_radio'],
  sinhala: ['bbc_sinhala_radio'],
  amharic: ['bbc_amharic_radio'],
  russian: ['bbc_russian_radio'],
  indonesia: ['bbc_indonesian_radio'],
  bengali: ['bbc_bangla_radio'],
  somali: ['bbc_somali_radio'],
  zhongwen: ['bbc_cantonese_radio'],
  burmese: ['bbc_burmese_radio'],
  afrique: ['bbc_afrique_radio'],
  gahuza: ['bbc_gahuza_radio'],
  yoruba: ['bbc_yoruba_radio'],
  hindi: ['bbc_hindi_radio'],
  tamil: ['bbc_tamil_radio'],
};

export const servicesWithTv = {
  hausa: ['bbc_hausa_tv'],
  persian: ['bbc_persian_tv'],
  urdu: ['bbc_urdu_tv'],
  gujarati: ['bbc_gujarati_tv'],
  pashto: ['bbc_pashto_tv'],
  uzbek: ['bbc_uzbek_tv'],
  swahili: ['bbc_swahili_tv'],
  kyrgyz: ['bbc_kyrgyz_tv'],
  russian: ['bbc_russian_tv'],
  somali: ['bbc_somali_tv'],
  ukrainian: ['bbc_ukrainian_tv'],
  burmese: ['bbc_burmese_tv'],
  marathi: ['bbc_marathi_tv'],
  telugu: ['bbc_telugu_tv'],
  afrique: ['bbc_afrique_tv'],
  hindi: ['bbc_hindi_tv'],
  tamil: ['bbc_tamil_tv'],
};
