export const CPS_LONG_ARTICLE_WITH_PNG_AND_VISJO =
  'WS-CPS_LONG_ARTICLE_WITH_PNG_AND_VISJO';
export const CPS_LONG_ARTICLE_YOUTUBE_EMBED =
  'WS-CPS_LONG_ARTICLE_YOUTUBE_EMBED';
export const CPS_MEDIUM_ARTICLE = 'WS-CPS_MEDIUM_ARTICLE';
export const CPS_SHORT_ARTICLE_YOUTUBE_EMBED =
  'WS-CPS_SHORT_ARTICLE_YOUTUBE_EMBED';
export const CPS_SHORT_ARTICLE = 'WS-CPS_SHORT_ARTICLE';
export const HOMEPAGE_SHORT = 'WS-HOMEPAGE_SHORT';
export const HOMEPAGE_LONG = 'WS-HOMEPAGE_LONG';
export const MEDIA_ASSET_AUDIO = 'WS-MEDIA_ASSET_AUDIO';
export const MEDIA_ASSET_VIDEO = 'WS-MEDIA_ASSET_VIDEO';
export const RADIO_PAGE = 'WS-RADIO';
export const PODCAST_PAGE = 'WS-PODCAST';
