/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service pashto
 * @pathname /pashto/media-23257523
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP pashto mediaAssetPage', runAmpTests);
