/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service tigrinya
 * @pathname /tigrinya/news-23263262
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP tigrinya mediaAssetPage', runAmpTests);
