/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service arabic
 * @pathname /arabic
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP arabic frontPage', runAmpTests);
