/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service arabic
 * @pathname /arabic
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical arabic frontPage', runCanonicalTests);
