/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service gahuza
 * @pathname /gahuza
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP gahuza frontPage', runAmpTests);
