/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service gahuza
 * @pathname /gahuza
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical gahuza frontPage', runCanonicalTests);
