/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service tigrinya
 * @pathname /tigrinya
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP tigrinya frontPage', runAmpTests);
