/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service tigrinya
 * @pathname /tigrinya
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical tigrinya frontPage', runCanonicalTests);
