import { Services } from '#app/models/types/global';

/**
 * We have opted to use an object instead of an array to circumvent Typescript's non exhaustive array type checking
 * Demo: https://www.typescriptlang.org/play/?#code/C4TwDgpgBAyhBOA3AlgYwgZygXigcgEMAzeZARwFcI8oAffAWwoDsATAexvrzGVYHNkzPAG4AUGID0kqAFEGYUFACC8eARA4ozdlAAqMKAnjt4WXADllATTGp2zDMCMLQcJGkyr1IAFywEFHQMAG0AXS1w8SkZAAUCeGBkAgAbFTUNLR19Q2NTcygrW3tHZzAEpNT3IK8MvwCPYPDIwhJyKjww6Okoaxs7BycoVJTqzwxvDX8xpojcENbSSmoAGkYWDjw1nj5BYS6JHr1waDwAIjB2FIwAawIzmmQsHWcCDAxkfmYCACMU6GAulAkHwM0weAAdAAKABMAGYYTCAJRQLR9YqDV51ADqyGAAAsLA5ZAAPJ7ACDMYBg6aBcbNeY8K63AidaLA6AWCAAdzBBT5dHwl2ud1EEhKQwSPlxBK5vLpwX8cr5DKgC2FLM6hxkxxBeAA3gBfR5YBhPD7MfhQAnQIhXFLsblCK1gEyQRLITBQEjsBjWk74ABKEHs8FYAB4+WszmcAHx4fzEJZUNZMNjsNa8ARCWEAdjhAE4Ubh0QNSi5FCA+QB5H4AKxDwH8wdDEaj+Dwsa0Ru6OoDBuGbWW-hjIigxqgTygZvezut+Nt9sdc9d7HdSS9Pr9HKDIdMbYVmGjcYT042GagWb2ecLxd6-QlZQqyVGh4wtYbqCbUBb+8jb+2TtuzEVEk3aCB-DwPAxENbV7wxcsRhretG2bPcw3-Rojw7LtcH1EDB2TCCOxWAi0w4SCtgIq8hEo0jYKAA
 */
const services: Record<Services, ''> = {
  afaanoromoo: '',
  afrique: '',
  amharic: '',
  arabic: '',
  archive: '',
  azeri: '',
  bengali: '',
  burmese: '',
  cymrufyw: '',
  dari: '',
  gahuza: '',
  gujarati: '',
  hausa: '',
  hindi: '',
  igbo: '',
  indonesia: '',
  japanese: '',
  korean: '',
  kyrgyz: '',
  magyarul: '',
  marathi: '',
  mundo: '',
  naidheachdan: '',
  nepali: '',
  news: '',
  newsround: '',
  pashto: '',
  persian: '',
  pidgin: '',
  polska: '',
  portuguese: '',
  punjabi: '',
  romania: '',
  russian: '',
  scotland: '',
  serbian: '',
  sinhala: '',
  somali: '',
  sport: '',
  swahili: '',
  tamil: '',
  telugu: '',
  thai: '',
  tigrinya: '',
  turkce: '',
  ukchina: '',
  ukrainian: '',
  urdu: '',
  uzbek: '',
  vietnamese: '',
  ws: '',
  yoruba: '',
  zhongwen: '',
};

export default Object.keys(services) as Services[];
