import { Services } from '#app/models/types/global';

const services: Record<Services, number> = {
  afaanoromoo: 1,
  afrique: 2,
  amharic: 3,
  arabic: 4,
  archive: 0,
  azeri: 5,
  bengali: 6,
  burmese: 7,
  cymrufyw: 0,
  dari: 8,
  gahuza: 9,
  gujarati: 10,
  hausa: 11,
  hindi: 12,
  igbo: 13,
  indonesia: 14,
  japanese: 15,
  korean: 16,
  kyrgyz: 17,
  magyarul: 18,
  marathi: 19,
  mundo: 20,
  naidheachdan: 0,
  nepali: 21,
  news: 0,
  newsround: 0,
  pashto: 22,
  persian: 23,
  pidgin: 24,
  polska: 25,
  portuguese: 26,
  punjabi: 27,
  romania: 28,
  russian: 29,
  scotland: 0,
  serbian: 30,
  sinhala: 31,
  somali: 32,
  sport: 0,
  swahili: 33,
  tamil: 34,
  telugu: 35,
  thai: 36,
  tigrinya: 37,
  turkce: 38,
  ukchina: 39,
  ukrainian: 40,
  urdu: 41,
  uzbek: 42,
  vietnamese: 43,
  ws: 0,
  yoruba: 44,
  zhongwen: 45,
};

export default Object.keys(services) as Services[];
