/**
 * @service zhongwen
 * @pathname /zhongwen/articles/c3xd4x9prgyo/trad
 *
 * THIS TEST SUITE WAS GENERATED BY A BUILD SCRIPT. DO NOT EDIT THIS FILE.
 */

import runCrossPlatformTests from '../../../../../pages/articles/crossPlatformTests';
import runAmpTests from '../../../../../pages/articles/ampTests';
describe(platform.toUpperCase(), () => {
  describe(pageType, () => {
    runCrossPlatformTests();
    runAmpTests();
  });
});
