/**
 * @service zhongwen
 * @pathname /zhongwen/articles/c3xd4x9prgyo/trad
 *
 * THIS TEST SUITE WAS GENERATED BY A BUILD SCRIPT. DO NOT EDIT THIS FILE.
 */

import runCoreTests from '../../../../../common/core.amp';
import runAnalyticsTests from '../../../../../common/analytics.amp';
runCoreTests();
runAnalyticsTests();
