/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service igbo
 * @pathname /igbo/articles/cr1lw620ygjo
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP igbo articles', runAmpTests);
