/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service korean
 * @pathname /korean/articles/c3mn1lvz65xo
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP korean articles', runAmpTests);
