/**
 * @service russian
 * @pathname /russian/articles/ck7pz7re3zgo
 *
 * THIS TEST SUITE WAS GENERATED BY A BUILD SCRIPT. DO NOT EDIT THIS FILE.
 */

import runCoreTests from '../../../../common/core.canonical';
import runAnalyticsTests from '../../../../common/analytics.canonical';
runCoreTests();
runAnalyticsTests();
