/**
 * @service igbo
 * @pathname /igbo/articles/cr1lw620ygjo
 *
 * THIS TEST SUITE WAS GENERATED BY A BUILD SCRIPT. DO NOT EDIT THIS FILE.
 */

import runCoreTests from '../../../../common/core.canonical';
import runAnalyticsTests from '../../../../common/analytics.canonical';
runCoreTests();
runAnalyticsTests();
