/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service swahili
 * @pathname /swahili
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP swahili frontPage', runAmpTests);
