/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service swahili
 * @pathname /swahili
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical swahili frontPage', runCanonicalTests);
