/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service afaanoromoo
 * @pathname /afaanoromoo/23149891
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP afaanoromoo mediaAssetPage', runAmpTests);
