/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service afaanoromoo
 * @pathname /afaanoromoo/23149891
 */

import runCanonicalTests from '../../../../pages/mediaAssetPage/canonicalTests';

describe('Canonical afaanoromoo mediaAssetPage', runCanonicalTests);
