/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service kyrgyz
 * @pathname /kyrgyz/media-23257484
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP kyrgyz mediaAssetPage', runAmpTests);
