/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service punjabi
 * @pathname /punjabi/media-23248705
 * @hasBulletedList true
 * @hasRelatedContent true
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP punjabi mediaAssetPage', runAmpTests);
