/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service punjabi
 * @pathname /punjabi/media-23248705
 * @hasBulletedList true
 * @hasRelatedContent true
 */

import runCanonicalTests from '../../../../pages/mediaAssetPage/canonicalTests';

describe('Canonical punjabi mediaAssetPage', runCanonicalTests);
