/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service vietnamese
 * @pathname /vietnamese/23222411
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP vietnamese mediaAssetPage', runAmpTests);
