/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service marathi
 * @pathname /marathi/articles/cp47g4myxz7o
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical marathi articles', runCanonicalTests);
