/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service ukrainian
 * @pathname /ukrainian/world-23087423
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP ukrainian mediaAssetPage', runAmpTests);
