/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service burmese
 * @pathname /burmese/media-23269011
 * @hasBulletedList true
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP burmese mediaAssetPage', runAmpTests);
