/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service burmese
 * @pathname /burmese/media-23269011
 * @hasBulletedList true
 */

import runCanonicalTests from '../../../../pages/mediaAssetPage/canonicalTests';

describe('Canonical burmese mediaAssetPage', runCanonicalTests);
