/**
 * @service igbo
 * @pathname /igbo/afirika-23252735
 *
 * THIS TEST SUITE WAS GENERATED BY A BUILD SCRIPT. DO NOT EDIT THIS FILE.
 */

import runCrossPlatformTests from '../../../../pages/storyPage/crossPlatformTests';
import runAmpTests from '../../../../pages/storyPage/ampTests';
import runCanonicalTests from '../../../../pages/storyPage/canonicalTests';
describe(`Story Page -`, () => {
  runCrossPlatformTests();
  if (platform === 'amp') {
    runAmpTests();
  }
  if (platform === 'canonical') {
    runCanonicalTests();
  }
});
