/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service indonesia
 * @pathname /indonesia
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP indonesia frontPage', runAmpTests);
