/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service indonesia
 * @pathname /indonesia
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical indonesia frontPage', runCanonicalTests);
