/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service nepali
 * @pathname /nepali/articles/cl90j9m3mn6o
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP nepali articles', runAmpTests);
