/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service japanese
 * @pathname /japanese/video-23248670
 * @hasBulletedList true
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP japanese mediaAssetPage', runAmpTests);
