#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

sh scripts/stopPushOnLatest.sh && sh scripts/upToDateWithLatest.sh && sh scripts/enforceVersions.sh && yarn test:unit -- --changedSince=latest && yarn test:integration && apache2-license-checker
