/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service tamil
 * @pathname /tamil/india-23268994
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP tamil mediaAssetPage', runAmpTests);
