/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service zhongwen
 * @pathname /zhongwen/articles/c3xd4x9prgyo/simp
 * @hasImageWithCaption false
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical zhongwen articles', runCanonicalTests);
