/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

/* eslint-disable react/no-unknown-property */

import { useGLTF } from '@react-three/drei';

import { getEnvConfig } from '#app/lib/utilities/getEnvConfig';

const {
  SIMORGH_PUBLIC_STATIC_ASSETS_ORIGIN,
  SIMORGH_PUBLIC_STATIC_ASSETS_PATH,
} = getEnvConfig();

const MESH_COLORS = [
  '#e6194b',
  '#3cb44b',
  '#ffe119',
  '#4363d8',
  '#f58231',
  '#911eb4',
  '#42d4f4',
  '#f032e6',
  '#bfef45',
  '#fabed4',
];

export function Globe(props) {
  const { nodes } = useGLTF(
    `${SIMORGH_PUBLIC_STATIC_ASSETS_ORIGIN}${SIMORGH_PUBLIC_STATIC_ASSETS_PATH}3d/Models/test_globe.glb`,
  );
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere001.geometry}>
        <meshBasicMaterial color={MESH_COLORS[0]} />
      </mesh>
      <mesh geometry={nodes.Sphere002.geometry}>
        <meshBasicMaterial color={MESH_COLORS[1]} />
      </mesh>
      <mesh geometry={nodes.Sphere003.geometry}>
        <meshBasicMaterial color={MESH_COLORS[2]} />
      </mesh>
      <mesh geometry={nodes.Sphere004.geometry}>
        <meshBasicMaterial color={MESH_COLORS[3]} />
      </mesh>
      <mesh geometry={nodes.Sphere005.geometry}>
        <meshBasicMaterial color={MESH_COLORS[4]} />
      </mesh>
      <mesh geometry={nodes.Sphere006.geometry}>
        <meshBasicMaterial color={MESH_COLORS[5]} />
      </mesh>
      <mesh geometry={nodes.Sphere007.geometry}>
        <meshBasicMaterial color={MESH_COLORS[6]} />
      </mesh>
      <mesh geometry={nodes.Sphere008.geometry}>
        <meshBasicMaterial color={MESH_COLORS[7]} />
      </mesh>
      <mesh geometry={nodes.Sphere009.geometry}>
        <meshBasicMaterial color={MESH_COLORS[8]} />
      </mesh>
      <mesh geometry={nodes.Sphere010.geometry}>
        <meshBasicMaterial color={MESH_COLORS[9]} />
      </mesh>
    </group>
  );
}

useGLTF.preload(
  `${SIMORGH_PUBLIC_STATIC_ASSETS_ORIGIN}${SIMORGH_PUBLIC_STATIC_ASSETS_PATH}3d/Models/test_globe.glb`,
);

export default Globe;
