/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service igbo
 * @pathname /igbo/media-23256786
 * @hasBulletedList true
 * @hasRelatedContent true
 */

import runAmpTests from '../../../../pages/mediaAssetPage/ampTests';

describe('AMP igbo mediaAssetPage', runAmpTests);
