/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service igbo
 * @pathname /igbo/media-23256786
 * @hasBulletedList true
 * @hasRelatedContent true
 */

import runCanonicalTests from '../../../../pages/mediaAssetPage/canonicalTests';

describe('Canonical igbo mediaAssetPage', runCanonicalTests);
