/*
 * Exported arrays of domains used in the CSP Utility
 */

export const bbcDomains = [
  '*.bbc.co.uk',
  '*.bbc.com',
  '*.bbci.co.uk',
  '*.bbci.com',
];

export const advertisingServiceCountryDomains = country =>
  [
    { iso: 'ae', domain: 'https://*.google.ae' },
    { iso: 'af', domain: 'https://*.google.com.af' },
    { iso: 'ar', domain: 'https://*.google.com.ar' },
    { iso: 'at', domain: 'https://*.google.at' },
    { iso: 'au', domain: 'https://*.google.com.au' },
    { iso: 'az', domain: 'https://*.google.az' },
    { iso: 'be', domain: 'https://*.google.be' },
    { iso: 'bo', domain: 'https://*.google.com.bo' },
    { iso: 'br', domain: 'https://*.google.com.br' },
    { iso: 'ca', domain: 'https://*.google.ca' },
    { iso: 'ch', domain: 'https://*.google.ch' },
    { iso: 'cl', domain: 'https://*.google.cl' },
    { iso: 'co', domain: 'https://*.google.com.co' },
    { iso: 'cv', domain: 'https://*.google.cv' },
    { iso: 'cy', domain: 'https://*.google.com.cy' },
    { iso: 'cz', domain: 'https://*.google.cz' },
    { iso: 'de', domain: 'https://*.google.de' },
    { iso: 'dk', domain: 'https://*.google.dk' },
    { iso: 'ec', domain: 'https://*.google.com.ec' },
    { iso: 'eg', domain: 'https://*.google.com.eg' },
    { iso: 'es', domain: 'https://*.google.es' },
    { iso: 'fi', domain: 'https://*.google.fi' },
    { iso: 'fr', domain: 'https://*.google.fr' },
    { iso: 'ge', domain: 'https://*.google.ge' },
    { iso: 'gt', domain: 'https://*.google.com.gt' },
    { iso: 'hk', domain: 'https://*.google.com.hk' },
    { iso: 'hn', domain: 'https://*.google.hn' },
    { iso: 'id', domain: 'https://*.google.co.id' },
    { iso: 'ie', domain: 'https://*.google.ie' },
    { iso: 'il', domain: 'https://*.google.co.il' },
    { iso: 'in', domain: 'https://*.google.co.in' },
    { iso: 'iq', domain: 'https://*.google.iq' },
    { iso: 'it', domain: 'https://*.google.it' },
    { iso: 'jo', domain: 'https://*.google.jo' },
    { iso: 'jp', domain: 'https://*.google.co.jp' },
    { iso: 'kh', domain: 'https://*.google.com.kh' },
    { iso: 'kr', domain: 'https://*.google.co.kr' },
    { iso: 'kz', domain: 'https://*.google.kz' },
    { iso: 'lk', domain: 'https://*.google.lk' },
    { iso: 'lv', domain: 'https://*.google.lv' },
    { iso: 'mm', domain: 'https://*.google.com.mm' },
    { iso: 'mt', domain: 'https://*.google.com.mt' },
    { iso: 'mx', domain: 'https://*.google.com.mx' },
    { iso: 'ng', domain: 'https://*.google.com.ng' },
    { iso: 'ni', domain: 'https://*.google.com.ni' },
    { iso: 'nl', domain: 'https://*.google.nl' },
    { iso: 'no', domain: 'https://*.google.no' },
    { iso: 'np', domain: 'https://*.google.com.np' },
    { iso: 'nz', domain: 'https://*.google.co.nz' },
    { iso: 'pe', domain: 'https://*.google.com.pe' },
    { iso: 'pk', domain: 'https://*.google.com.pk' },
    { iso: 'pl', domain: 'https://*.google.pl' },
    { iso: 'pr', domain: 'https://*.google.com.pr' },
    { iso: 'py', domain: 'https://*.google.com.py' },
    { iso: 'ro', domain: 'https://*.google.com.ro' },
    { iso: 'ru', domain: 'https://*.google.ru' },
    { iso: 'sa', domain: 'https://*.google.com.sa' },
    { iso: 'se', domain: 'https://*.google.se' },
    { iso: 'sg', domain: 'https://*.google.com.sg' },
    { iso: 'so', domain: 'https://*.google.so' },
    { iso: 'sv', domain: 'https://*.google.com.sv' },
    { iso: 'tr', domain: 'https://*.google.com.tr' },
    { iso: 'tw', domain: 'https://*.google.com.tw' },
    { iso: 'tz', domain: 'https://*.google.co.tz' },
    { iso: 'ua', domain: 'https://*.google.com.ua' },
    { iso: 'uy', domain: 'https://*.google.com.uy' },
    { iso: 'vn', domain: 'https://*.google.com.vn' },
    { iso: 've', domain: 'https://*.google.co.ve' },
  ].filter(({ iso }) => iso === country);
