/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service thai
 * @pathname /thai
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP thai frontPage', runAmpTests);
