/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service thai
 * @pathname /thai
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical thai frontPage', runCanonicalTests);
