/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service igbo
 * @pathname /igbo
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP igbo frontPage', runAmpTests);
