/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service igbo
 * @pathname /igbo
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical igbo frontPage', runCanonicalTests);
