/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service hindi
 * @pathname /hindi
 */

import runAmpTests from '../../../../pages/frontPage/ampTests';

describe('AMP hindi frontPage', runAmpTests);
