/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service hindi
 * @pathname /hindi
 */

import runCanonicalTests from '../../../../pages/frontPage/canonicalTests';

describe('Canonical hindi frontPage', runCanonicalTests);
