/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service azeri
 * @pathname /azeri/articles/c5k08pqnzexo
 */

import runCanonicalTests from '../../../../pages/articles/canonicalTests';

describe('Canonical azeri articles', runCanonicalTests);
