name: Dependabot Code Review
on:
  pull_request:
    # types:
    #   - opened
    branches:
      - '**'

jobs:
  run:
    name: Request Code Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Post Slack Message
        uses: slackapi/slack-github-action@v2.1.0
        with:
          payload-file-path: '.github/workflows/dependabot-code-review/payload.json'
          payload-templated: true
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
