name: Dependabot Code Review
on:
  pull_request:
    # types:
    #   - opened
    branches:
      - '**'

jobs:
  run:
    name: Leave a kind message after updates
    runs-on: ubuntu-latest
    steps:
      - name: Greet the reader
        uses: slackapi/slack-github-action@v2.1.0
        with:
          payload-file-path: '.github/workflows/dependabot-code-review/payload.json'
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
