name: Playwright E2E - Simorgh
on:
  pull_request:
    branches:
      - '**'
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    env:
      CI: true
      LOG_LEVEL: 'error'

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ws-nextjs-app/node_modules
          key: node-modules-${{ hashFiles('yarn.lock', 'ws-nextjs-app/yarn.lock') }}

      - name: Install Node Modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          rm -rf node_modules
          git config --global user.name "${{ secrets.WS_UTF_USERNAME }}"
          git config --global user.email "${{ secrets.WS_UTF_EMAIL }}"
          git config --global url.https://${{ secrets.WS_UTF_AUTH }}@github.com/.insteadOf https://github.com/
          ./scripts/installNodeModules.sh

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: ws-nextjs-app
        run: HEADLESS=true npx playwright test --project="WorldService - Chrome"

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ws-nextjs-app/playwright-report/
          retention-days: 30
