name: Unit Tests - Express
on:
  pull_request:
    branches:
      - '**'
permissions:
  contents: read

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ws-nextjs-app/node_modules
          key: node-modules-${{ hashFiles('yarn.lock', 'ws-nextjs-app/yarn.lock') }}

      - name: Install Node Modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./scripts/installNodeModules.sh

      - name: Simorgh Express Build
        run: yarn build

      - name: Save Simorgh Express Build
        uses: actions/upload-artifact@v4
        with:
          name: simorgh-build
          if-no-files-found: error
          path: build

  build:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x]
        containers: [1, 2, 3, 4]
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ws-nextjs-app/node_modules
          key: node-modules-${{ hashFiles('yarn.lock', 'ws-nextjs-app/yarn.lock') }}

      - name: Download the Simorgh build folder
        uses: actions/download-artifact@v4
        with:
          name: simorgh-build
          path: build

      - name: Install Node Modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./scripts/installNodeModules.sh

      - name: Unit Tests
        run: |
          export INDEX=$((${{ strategy.job-index }} + 1))
          yarn test:unit:ci --shard=$INDEX/${{ strategy.job-total }}
