/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service yoruba
 * @pathname /yoruba/articles/clw06m0nj8qo
 */

import runAmpTests from '../../../../pages/articles/ampTests';

describe('AMP yoruba articles', runAmpTests);
