/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service mundo
 * @pathname /mundo/popular/read
 */

import runAmpTests from '../../../../pages/mostReadPage/ampTests';

describe('AMP mundo mostReadPage', runAmpTests);
