/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service mundo
 * @pathname /mundo/popular/read
 */

import runCanonicalTests from '../../../../pages/mostReadPage/canonicalTests';

describe('Canonical mundo mostReadPage', runCanonicalTests);
