/**
 * WARNING: DO NOT EDIT. This file is automatically generated by src/integration/utils/runTests/writeTestFiles/writeTestFile.js
 * @service korean
 * @pathname /korean/bbc_korean_radio/liveradio
 */

import runAmpTests from '../../../../pages/liveRadio/ampTests';

describe('AMP korean liveRadio', runAmpTests);
